NIFTY_AUTO = ['HEROMOTOCO.NS', 'BAJAJ-AUTO.NS', 'MARUTI.NS', 'EICHERMOT.NS', 'SONACOMS.NS', 'ASHOKLEY.NS', 'M&M.NS',
              'MOTHERSON.NS', 'TATAMOTORS.NS', 'TVSMOTOR.NS', 'MRF.NS', 'TIINDIA.NS', 'BOSCHLTD.NS', 'BHARATFORG.NS',
              'BALKRISIND.NS']
NIFTY_DIVIDEND_OPPORTUNITIES_50 = ['IRFC.NS', 'BSE.NS', 'HEROMOTOCO.NS', 'VEDL.NS', 'COALINDIA.NS', 'CHAMBLFERT.NS',
                                   'BAJAJ-AUTO.NS', 'ACC.NS', 'PFC.NS', 'PETRONET.NS', 'UNIONBANK.NS', 'BANKINDIA.NS',
                                   'ONGC.NS', 'NTPC.NS', 'LICHSGFIN.NS', 'REDINGTON.NS', 'RECLTD.NS', 'NATIONALUM.NS',
                                   'SAIL.NS', 'HCLTECH.NS', 'MANAPPURAM.NS', 'COLPAL.NS', 'CANBK.NS', 'BATAINDIA.NS',
                                   'INDIANB.NS', 'INDUSTOWER.NS', 'ANGELONE.NS', 'GAIL.NS', 'TECHM.NS', 'MPHASIS.NS',
                                   'NHPC.NS', 'MUTHOOTFIN.NS', 'HAL.NS', 'TCS.NS', 'IOC.NS', 'TATASTEEL.NS',
                                   'BRITANNIA.NS', 'MCX.NS', 'POWERGRID.NS', 'BEL.NS', 'JSWSTEEL.NS', 'HINDUNILVR.NS',
                                   'ITC.NS', 'INFY.NS', 'CUMMINSIND.NS', 'BAJAJHLDNG.NS', 'BPCL.NS', 'KARURVYSYA.NS',
                                   'HINDPETRO.NS', 'MGL.NS']
NIFTY_PSE = ['OIL.NS', 'COALINDIA.NS', 'PFC.NS', 'LICI.NS', 'ONGC.NS', 'NTPC.NS', 'RECLTD.NS', 'SAIL.NS', 'GAIL.NS',
             'NHPC.NS', 'CONCOR.NS', 'NMDC.NS', 'IRCTC.NS', 'HAL.NS', 'BHEL.NS', 'IOC.NS', 'POWERGRID.NS', 'BEL.NS',
             'BPCL.NS', 'HINDPETRO.NS']
NIFTY_INDIA_MANUFACTURING = ['GRAPHITE.NS', 'LAURUSLABS.NS', 'MSUMI.NS', 'HEROMOTOCO.NS', 'VEDL.NS', 'CHAMBLFERT.NS',
                             'BAJAJ-AUTO.NS', 'POLYCAB.NS', 'MARUTI.NS', 'CROMPTON.NS', 'AIAENG.NS', 'FLUOROCHEM.NS',
                             'DIVISLAB.NS', 'HINDZINC.NS', 'EICHERMOT.NS', 'UPL.NS', 'SONACOMS.NS', 'SCHAEFFLER.NS',
                             'HINDCOPPER.NS', 'DIXON.NS', 'ASHOKLEY.NS', 'M&M.NS', 'SKFINDIA.NS', 'MOTHERSON.NS',
                             'DRREDDY.NS', 'TATAMOTORS.NS', 'SIEMENS.NS', 'BATAINDIA.NS', 'VOLTAS.NS', 'TRIDENT.NS',
                             'TORNTPHARM.NS', 'ABB.NS', 'TATACHEM.NS', 'MRF.NS', 'LINDEINDIA.NS', 'COROMANDEL.NS',
                             'TIINDIA.NS', 'ASTRAL.NS', 'HONAUT.NS', 'BOSCHLTD.NS', 'MAZDOCK.NS', 'HAVELLS.NS',
                             'RELAXO.NS', 'LUPIN.NS', 'KPRMILL.NS', 'KAJARIACER.NS', 'RELIANCE.NS', 'SUPREMEIND.NS',
                             'BHARATFORG.NS', 'HAL.NS', 'BALKRISIND.NS', 'IOC.NS', 'PAGEIND.NS', 'SUNPHARMA.NS',
                             'TATASTEEL.NS', 'ATUL.NS', 'BEL.NS', 'HINDALCO.NS', 'JSWSTEEL.NS', 'GRINDWELL.NS',
                             'CIPLA.NS', 'ESCORTS.NS', 'CGPOWER.NS', 'NAVINFLUOR.NS', 'PIDILITIND.NS', 'CUMMINSIND.NS',
                             'SOLARINDS.NS', 'PIIND.NS', 'DEEPAKNTR.NS', 'SRF.NS', 'APLAPOLLO.NS', 'BPCL.NS']
NIFTY_GROWTH_SECTORS_15 = ['MARUTI.NS', 'EICHERMOT.NS', 'ASHOKLEY.NS', 'HCLTECH.NS', 'TATACONSUM.NS', 'TITAN.NS',
                           'WIPRO.NS', 'TVSMOTOR.NS', 'TECHM.NS', 'TCS.NS', 'SUNPHARMA.NS', 'BRITANNIA.NS',
                           'HINDUNILVR.NS', 'CIPLA.NS', 'ITC.NS']
NIFTY100_LIQUID_15 = ['MARUTI.NS', 'BAJFINANCE.NS', 'BHARTIARTL.NS', 'BAJAJFINSV.NS', 'HCLTECH.NS', 'INDUSINDBK.NS',
                      'TITAN.NS', 'TATAMOTORS.NS', 'AXISBANK.NS', 'SBIN.NS', 'TECHM.NS', 'RELIANCE.NS', 'TATASTEEL.NS',
                      'ADANIPORTS.NS', 'ADANIENT.NS']
NIFTY50_EQUAL_WEIGHT = ['HEROMOTOCO.NS', 'COALINDIA.NS', 'BAJAJ-AUTO.NS', 'MARUTI.NS', 'DIVISLAB.NS', 'ONGC.NS',
                        'EICHERMOT.NS', 'BAJFINANCE.NS', 'UPL.NS', 'BHARTIARTL.NS', 'NTPC.NS', 'BAJAJFINSV.NS',
                        'HCLTECH.NS', 'HDFCLIFE.NS', 'M&M.NS', 'TATACONSUM.NS', 'INDUSINDBK.NS', 'DRREDDY.NS',
                        'TITAN.NS', 'ICICIBANK.NS', 'TATAMOTORS.NS', 'WIPRO.NS', 'AXISBANK.NS', 'KOTAKBANK.NS',
                        'ASIANPAINT.NS', 'SBILIFE.NS', 'SBIN.NS', 'TECHM.NS', 'ULTRACEMCO.NS', 'LT.NS', 'HDFC.NS',
                        'HDFCBANK.NS', 'RELIANCE.NS', 'NESTLEIND.NS', 'TCS.NS', 'SUNPHARMA.NS', 'TATASTEEL.NS',
                        'ADANIPORTS.NS', 'BRITANNIA.NS', 'GRASIM.NS', 'POWERGRID.NS', 'HINDALCO.NS', 'JSWSTEEL.NS',
                        'HINDUNILVR.NS', 'CIPLA.NS', 'ITC.NS', 'INFY.NS', 'APOLLOHOSP.NS', 'ADANIENT.NS', 'BPCL.NS']
NIFTY_PSU_BANK = ['UCOBANK.NS', 'MAHABANK.NS', 'PSB.NS', 'IOB.NS', 'CENTRALBK.NS', 'UNIONBANK.NS', 'BANKINDIA.NS',
                  'PNB.NS', 'CANBK.NS', 'INDIANB.NS', 'SBIN.NS', 'BANKBARODA.NS']
NIFTY_ALPHA_LOW_VOLATILITY_30 = ['BAJAJ-AUTO.NS', 'AMBUJACEM.NS', 'PFC.NS', 'BHARTIARTL.NS', 'NTPC.NS', 'HCLTECH.NS',
                                 'M&M.NS', 'TATACONSUM.NS', 'COLPAL.NS', 'TITAN.NS', 'ICICIBANK.NS', 'SIEMENS.NS',
                                 'SBILIFE.NS', 'SBIN.NS', 'LT.NS', 'DABUR.NS', 'RELIANCE.NS', 'NESTLEIND.NS',
                                 'MARICO.NS', 'TCS.NS', 'PAGEIND.NS', 'SUNPHARMA.NS', 'ALKEM.NS', 'BRITANNIA.NS',
                                 'POWERGRID.NS', 'HINDUNILVR.NS', 'CIPLA.NS', 'ITC.NS', 'PIDILITIND.NS',
                                 'CUMMINSIND.NS']
NIFTY_OIL_AND_GAS = ['OIL.NS', 'PETRONET.NS', 'ONGC.NS', 'CASTROLIND.NS', 'GAIL.NS', 'GUJGASLTD.NS', 'RELIANCE.NS',
                     'AEGISCHEM.NS', 'IOC.NS', 'GSPL.NS', 'IGL.NS', 'ATGL.NS', 'BPCL.NS', 'HINDPETRO.NS', 'MGL.NS']
NIFTY_MIDCAP_50 = ['IDEA.NS', 'BANDHANBNK.NS', 'POLYCAB.NS', 'M&MFIN.NS', 'PFC.NS', 'SHRIRAMFIN.NS', 'PETRONET.NS',
                   'LTTS.NS', 'PNB.NS', 'LICHSGFIN.NS', 'GODREJPROP.NS', 'RECLTD.NS', 'SAIL.NS', 'ASHOKLEY.NS',
                   'BIOCON.NS', 'IDFCFIRSTB.NS', 'ZEEL.NS', 'BATAINDIA.NS', 'COFORGE.NS', 'TVSMOTOR.NS', 'VOLTAS.NS',
                   'ABBOTINDIA.NS', 'UBL.NS', 'FEDERALBNK.NS', 'MRF.NS', 'OFSS.NS', 'GUJGASLTD.NS', 'MFSL.NS',
                   'MPHASIS.NS', 'ASTRAL.NS', 'HONAUT.NS', 'AUROPHARMA.NS', 'CONCOR.NS', 'LUPIN.NS', 'ZYDUSLIFE.NS',
                   'JINDALSTEL.NS', 'OBEROIRLTY.NS', 'NMDC.NS', 'BHARATFORG.NS', 'TATACOMM.NS', 'BALKRISIND.NS',
                   'ALKEM.NS', 'INDHOTEL.NS', 'JUBLFOOD.NS', 'ESCORTS.NS', 'CUMMINSIND.NS', 'TRENT.NS', 'PERSISTENT.NS',
                   'AUBANK.NS', 'HINDPETRO.NS']
NIFTY_ENERGY = ['COALINDIA.NS', 'TATAPOWER.NS', 'ONGC.NS', 'NTPC.NS', 'RELIANCE.NS', 'IOC.NS', 'POWERGRID.NS',
                'BPCL.NS', 'ADANIGREEN.NS', 'ADANITRANS.NS']
NIFTY_INDIA_CONSUMPTION = ['DMART.NS', 'HEROMOTOCO.NS', 'BAJAJ-AUTO.NS', 'MARUTI.NS', 'CROMPTON.NS', 'TATAPOWER.NS',
                           'EICHERMOT.NS', 'BHARTIARTL.NS', 'DLF.NS', 'M&M.NS', 'TATACONSUM.NS', 'COLPAL.NS',
                           'TITAN.NS', 'ZEEL.NS', 'ASIANPAINT.NS', 'HAVELLS.NS', 'DABUR.NS', 'NESTLEIND.NS',
                           'MARICO.NS', 'PAGEIND.NS', 'GODREJCP.NS', 'BRITANNIA.NS', 'MCDOWELL-N.NS', 'JUBLFOOD.NS',
                           'HINDUNILVR.NS', 'NAUKRI.NS', 'ITC.NS', 'TRENT.NS', 'APOLLOHOSP.NS', 'ADANITRANS.NS']
NIFTY_SMALLCAP_250 = ['RVNL.NS', 'BCG.NS', 'JBMA.NS', 'LXCHEM.NS', 'VAIBHAVGBL.NS', 'BALAMINES.NS', 'TANLA.NS',
                      'UCOBANK.NS', 'PNBHOUSING.NS', 'POLYPLEX.NS', 'GUJALKALI.NS', 'RTNINDIA.NS', 'PPLPHARMA.NS',
                      'WELSPUNIND.NS', 'AVANTIFEED.NS', 'INDIGOPNTS.NS', 'CAMS.NS', 'TCNSBRANDS.NS', 'GRAPHITE.NS',
                      'TEJASNET.NS', 'FACT.NS', 'OLECTRA.NS', 'IEX.NS', 'PRSMJOHNSN.NS', 'MAHABANK.NS', 'JUBLPHARMA.NS',
                      'STLTECH.NS', 'EASEMYTRIP.NS', 'LUXIND.NS', 'LATENTVIEW.NS', 'BSE.NS', 'HEG.NS', 'KSB.NS',
                      'SHYAMMETL.NS', 'DELTACORP.NS', 'TV18BRDCST.NS', 'APARINDS.NS', 'IBREALEST.NS', 'DATAPATTNS.NS',
                      'EDELWEISS.NS', 'DEEPAKFERT.NS', 'GNFC.NS', 'CENTURYTEX.NS', 'NETWORK18.NS', 'IOB.NS', 'IDBI.NS',
                      'SUNTECK.NS', 'GRINFRA.NS', 'RENUKA.NS', 'GODREJAGRO.NS', 'HUDCO.NS', 'CHEMPLASTS.NS',
                      'INTELLECT.NS', 'MHRIL.NS', 'CSBBANK.NS', 'JUBLINGREA.NS', 'WELCORP.NS', 'BALRAMCHIN.NS',
                      'CENTRALBK.NS', 'MAHINDCIE.NS', 'MOTILALOFS.NS', 'GALAXYSURF.NS', 'TRIVENI.NS', 'JMFINANCIL.NS',
                      'SUZLON.NS', 'RCF.NS', 'VTL.NS', 'CANFINHOME.NS', 'CHAMBLFERT.NS', 'SONATSOFTW.NS', 'MMTC.NS',
                      'GLENMARK.NS', 'NATCOPHARM.NS', 'SWSOLAR.NS', 'BORORENEW.NS', 'INGERRAND.NS', 'MRPL.NS', 'RBA.NS',
                      'RAIN.NS', 'HLEGLAS.NS', 'CDSL.NS', 'VARROC.NS', 'BBTC.NS', 'BSOFT.NS', 'EIDPARRY.NS',
                      'PRINCEPIPE.NS', 'DCMSHRIRAM.NS', 'CESC.NS', 'BIRLACORPN.NS', 'UFLEX.NS', 'RBLBANK.NS',
                      'GRANULES.NS', 'GSFC.NS', 'IBULHSGFIN.NS', 'MAHLOG.NS', 'TCIEXP.NS', 'KFINTECH.NS', 'CCL.NS',
                      'FDC.NS', 'CUB.NS', 'RALLIS.NS', 'TTKPRESTIG.NS', 'SHARDACROP.NS', 'MAPMYINDIA.NS',
                      'TATAINVEST.NS', 'FIVESTAR.NS', 'EQUITASBNK.NS', 'HIKAL.NS', 'JAMNAAUTO.NS', 'ASAHIINDIA.NS',
                      'JINDWORLD.NS', 'MFL.NS', 'ECLERX.NS', 'AMARAJABAT.NS', 'COCHINSHIP.NS', 'NUVOCO.NS',
                      'MTARTECH.NS', 'REDINGTON.NS', 'HINDCOPPER.NS', 'ENGINERSIN.NS', 'CASTROLIND.NS', 'UTIAMC.NS',
                      'ITI.NS', 'ASTERDM.NS', 'NATIONALUM.NS', 'AMBER.NS', 'MAHLIFE.NS', 'VGUARD.NS', 'JKLAKSHMI.NS',
                      'GREENPANEL.NS', 'WESTLIFE.NS', 'EXIDEIND.NS', 'QUESS.NS', 'HFCL.NS', 'GAEL.NS', 'AARTIDRUGS.NS',
                      'VIJAYA.NS', 'INFIBEAM.NS', 'KRBL.NS', 'SANOFI.NS', 'NCC.NS', 'IDFC.NS', 'IFBIND.NS',
                      'MANAPPURAM.NS', 'RITES.NS', 'CARBORUNIV.NS', 'INDIACEM.NS', 'NOCIL.NS', 'SOBHA.NS', 'JKPAPER.NS',
                      'FINPIPE.NS', 'GPPL.NS', 'RAINBOW.NS', 'ZENSARTECH.NS', 'BEML.NS', 'NBCC.NS', 'SUPRAJIT.NS',
                      'BRIGADE.NS', 'NAZARA.NS', 'ZYDUSWELL.NS', 'ROSSARI.NS', 'VMART.NS', 'KENNAMET.NS',
                      'METROPOLIS.NS', 'CREDITACC.NS', 'KNRCON.NS', 'BLUESTARCO.NS', 'FINCABLES.NS', 'VIPIND.NS',
                      'RATNAMANI.NS', 'ANGELONE.NS', 'CYIENT.NS', 'GMMPFAUDLR.NS', 'CERA.NS', 'LEMONTREE.NS', 'PCBL.NS',
                      'GESHIP.NS', 'NLCINDIA.NS', 'KALYANKJIL.NS', 'MAZDOCK.NS', 'SHOPERSTOP.NS', 'LAXMIMACH.NS',
                      'CEATLTD.NS', 'KEI.NS', 'PRAJIND.NS', 'SPARC.NS', 'INDIAMART.NS', 'BLS.NS', 'BDL.NS', 'CHALET.NS',
                      'BAJAJELEC.NS', 'SWANENERGY.NS', 'AEGISCHEM.NS', 'CENTURYPLY.NS', 'HGS.NS', 'GARFIBRES.NS',
                      'JYOTHYLAB.NS', 'SUVENPHAR.NS', 'MCX.NS', 'CHOLAHLDNG.NS', 'RHIM.NS', 'BASF.NS', 'JSL.NS',
                      'IRB.NS', 'CAMPUS.NS', 'MASTEK.NS', 'TMB.NS', 'EIHOTEL.NS', 'FSL.NS', 'APLLTD.NS', 'ELGIEQUIP.NS',
                      'SJVN.NS', 'GSPL.NS', 'PNCINFRA.NS', 'ROUTE.NS', 'KIMS.NS', 'SAPPHIRE.NS', 'NH.NS', 'APTUS.NS',
                      'RADICO.NS', 'POLYMED.NS', 'PVR.NS', 'BIKAJI.NS', 'KEC.NS', 'AETHER.NS', 'JBCHEPHARM.NS',
                      'EPL.NS', 'TCI.NS', 'POWERINDIA.NS', 'TEAMLEASE.NS', 'JUSTDIAL.NS', 'GOCOLORS.NS', 'ACI.NS',
                      'TRITURBINE.NS', 'RAYMOND.NS', '360ONE.NS', 'MEDPLUS.NS', 'ANURAS.NS', 'RUSTOMJEE.NS', 'IIFL.NS',
                      'GODFRYPHLP.NS', 'KALPATPOWR.NS', 'HOMEFIRST.NS', 'CRAFTSMAN.NS', 'KARURVYSYA.NS', 'MEDANTA.NS',
                      'ORIENTELEC.NS', 'MGL.NS', 'CGCL.NS', 'KPITTECH.NS']
NIFTY_SMALLCAP_50 = ['RVNL.NS', 'LXCHEM.NS', 'BALAMINES.NS', 'UCOBANK.NS', 'WELSPUNIND.NS', 'CAMS.NS', 'GRAPHITE.NS',
                     'IEX.NS', 'MAHABANK.NS', 'EASEMYTRIP.NS', 'LATENTVIEW.NS', 'BSE.NS', 'GNFC.NS', 'IOB.NS',
                     'IDBI.NS', 'RENUKA.NS', 'JUBLINGREA.NS', 'SUZLON.NS', 'CHAMBLFERT.NS', 'MRPL.NS', 'CDSL.NS',
                     'BSOFT.NS', 'CESC.NS', 'BIRLACORPN.NS', 'CUB.NS', 'AMARAJABAT.NS', 'REDINGTON.NS', 'HINDCOPPER.NS',
                     'UTIAMC.NS', 'NATIONALUM.NS', 'HFCL.NS', 'IDFC.NS', 'MANAPPURAM.NS', 'METROPOLIS.NS',
                     'ANGELONE.NS', 'CYIENT.NS', 'MAZDOCK.NS', 'BDL.NS', 'BAJAJELEC.NS', 'IRB.NS', 'CAMPUS.NS',
                     'ROUTE.NS', 'RADICO.NS', 'PVR.NS', 'BIKAJI.NS', 'JBCHEPHARM.NS', 'MEDPLUS.NS', 'ANURAS.NS',
                     'MEDANTA.NS', 'KPITTECH.NS']
NIFTY_MICROCAP_250 = ['DHANI.NS', 'MOL.NS', 'FAIRCHEMOR.NS', 'GATI.NS', 'MANALIPETC.NS', 'JINDALPOLY.NS', 'FILATEX.NS',
                      'RTNPOWER.NS', 'HERITGFOOD.NS', 'HIL.NS', 'HCC.NS', 'TIPSINDLTD.NS', 'COSMOFIRST.NS',
                      'ASTRAMICRO.NS', 'POKARNA.NS', 'BECTORFOOD.NS', 'KAYNES.NS', 'CAMLINFINE.NS', 'CIGNITITEC.NS',
                      'DCXINDIA.NS', 'SIS.NS', 'HINDOILEXP.NS', 'GTLINFRA.NS', 'KRSNAA.NS', 'IOLCP.NS', 'HERANBA.NS',
                      'BOMDYEING.NS', 'MINDACORP.NS', 'FORCEMOT.NS', 'HEMIPROP.NS', 'GRMOVER.NS', 'ADVENZYMES.NS',
                      'SOUTHBANK.NS', 'MAHSEAMLES.NS', 'EMUDHRA.NS', 'RAJRATAN.NS', 'SARDAEN.NS', 'STAR.NS',
                      'ALOKINDS.NS', 'VSTTILLERS.NS', 'DCAL.NS', 'SOTL.NS', 'PRICOLLTD.NS', 'RPOWER.NS', 'AGI.NS',
                      'CARTRADE.NS', 'KIRIINDUS.NS', 'HNDFDS.NS', 'JWL.NS', 'VENKEYS.NS', 'ORIENTCEM.NS',
                      'THOMASCOOK.NS', 'BAJAJHIND.NS', 'KIRLOSBROS.NS', 'RELIGARE.NS', 'MANINFRA.NS', 'MAYURUNIQ.NS',
                      'JPPOWER.NS', 'TIMETECHNO.NS', 'SCHNEIDER.NS', 'DALMIASUG.NS', 'TVTODAY.NS', 'RUPA.NS',
                      'DOLLAR.NS', 'ELECTCAST.NS', 'WELENT.NS', 'BFUTILITIE.NS', 'NEULANDLAB.NS', 'STYRENIX.NS',
                      'TIRUMALCHM.NS', 'UJJIVANSFB.NS', 'BEPL.NS', 'IFCI.NS', 'VAKRANGEE.NS', 'ISGEC.NS', 'PURVA.NS',
                      'SIYSIL.NS', 'SAFARI.NS', 'CHENNPETRO.NS', 'MSTCLTD.NS', 'TIDEWATER.NS', 'WOCKPHARMA.NS',
                      'SUPRIYA.NS', 'NAVA.NS', 'DBREALTY.NS', 'VALIANTORG.NS', 'IRCON.NS', 'SURYAROSNI.NS',
                      'RAILTEL.NS', 'ARVIND.NS', 'DWARKESH.NS', 'IPL.NS', 'GREAVESCOT.NS', 'AMIORG.NS', 'GMDCLTD.NS',
                      'HCG.NS', 'WABAG.NS', 'SOLARA.NS', 'OPTIEMUS.NS', 'ACCELYA.NS', 'EMIL.NS', 'VOLTAMP.NS',
                      'GREENPLY.NS', 'SSWL.NS', 'KCP.NS', 'ANANTRAJ.NS', 'NESCO.NS', 'DBL.NS', 'HATHWAY.NS', 'ICIL.NS',
                      'SYRMA.NS', 'STOVEKRAFT.NS', 'WSTCSTPAPR.NS', 'CONFIPET.NS', 'ASHOKA.NS', 'SPICEJET.NS', 'DEN.NS',
                      'PRIVISCL.NS', 'MOLDTKPAC.NS', 'NFL.NS', 'JTEKTINDIA.NS', 'GPIL.NS', 'GLS.NS', 'MOREPENLAB.NS',
                      'GATEWAY.NS', 'GUFICBIO.NS', 'GRAVITA.NS', 'PCJEWELLER.NS', 'MOIL.NS', 'PARAS.NS', 'HBLPOWER.NS',
                      'DATAMATICS.NS', 'LGBBROSLTD.NS', 'CAPLIPOINT.NS', 'GABRIEL.NS', 'APCOTEXIND.NS', 'PTC.NS',
                      'JAICORPLTD.NS', 'PGEL.NS', 'DAAWAT.NS', 'ELECON.NS', 'J&KBANK.NS', 'NRBBEARING.NS',
                      'MAITHANALL.NS', 'ANDHRSUGAR.NS', 'GLOBUSSPR.NS', 'TARSONS.NS', 'JINDALSAW.NS', 'FIEMIND.NS',
                      'CMSINFO.NS', 'SHILPAMED.NS', 'HSCL.NS', 'INOXWIND.NS', 'PDSL.NS', 'MIDHANI.NS', 'ROLEXRINGS.NS',
                      'VSTIND.NS', 'ARVINDFASN.NS', 'BALMLAWRIE.NS', 'JISLJALEQS.NS', 'RATEGAIN.NS', 'DISHTV.NS',
                      'ACE.NS', 'SULA.NS', 'INDOCO.NS', 'KKCL.NS', 'USHAMART.NS', 'SEQUENT.NS', 'ETHOSLTD.NS',
                      'BAJAJCON.NS', 'FINOPB.NS', 'TATVA.NS', 'ERIS.NS', 'RELINFRA.NS', 'PGHL.NS', 'MARKSANS.NS',
                      'THYROCARE.NS', 'UJJIVAN.NS', 'FCL.NS', 'IMFA.NS', 'POWERMECH.NS', 'TATASTLLP.NS', 'HGINFRA.NS',
                      'PARADEEP.NS', 'HARSHA.NS', 'SUBEXLTD.NS', 'PRUDENT.NS', 'PSPPROJECT.NS', 'JPASSOCIAT.NS',
                      'BUTTERFLY.NS', 'DCBBANK.NS', 'SHAREINDIA.NS', 'NAVNETEDUL.NS', 'KIRLFER.NS', 'KSCL.NS',
                      'EVEREADY.NS', 'CARYSIL.NS', 'HEIDELBERG.NS', 'SHANTIGEAR.NS', 'SOMANYCERA.NS', 'NEOGEN.NS',
                      'PANAMAPET.NS', 'CARERATING.NS', 'TATAMETALI.NS', 'SPANDANA.NS', 'SAGCEM.NS', 'JKIL.NS',
                      'GOKEX.NS', 'TINPLATE.NS', 'ANANDRATHI.NS', 'KOLTEPATIL.NS', 'JKTYRE.NS', 'LANDMARK.NS',
                      'KIRLOSENG.NS', 'GOODYEAR.NS', 'ICRA.NS', 'SUDARSCHEM.NS', 'SBCL.NS', 'FUSION.NS', 'TEGA.NS',
                      'ASTRAZEN.NS', 'STARCEMENT.NS', 'SANSERA.NS', 'VESUVIUS.NS', 'MMFL.NS', 'UNIPARTS.NS',
                      'TECHNOE.NS', 'UNICHEMLAB.NS', 'INDIAGLYCO.NS', 'ESABINDIA.NS', 'IONEXCHANG.NS', 'SYMPHONY.NS',
                      'AKZOINDIA.NS', 'MAHSCOOTER.NS', 'RKFORGE.NS', 'NEWGEN.NS', 'GRSE.NS', 'PAISALO.NS', 'VRLLOG.NS',
                      'AUTOAXLES.NS', 'HINDWAREAP.NS', 'BESTAGRO.NS', 'LAOPALA.NS', 'APOLLOPIPE.NS', 'SPLPETRO.NS',
                      'MASFIN.NS', 'ASTEC.NS', 'NDTV.NS', 'BARBEQUE.NS', 'KTKBANK.NS']
NIFTY_METAL = ['WELCORP.NS', 'VEDL.NS', 'HINDZINC.NS', 'HINDCOPPER.NS', 'NATIONALUM.NS', 'SAIL.NS', 'RATNAMANI.NS',
               'JINDALSTEL.NS', 'NMDC.NS', 'TATASTEEL.NS', 'JSL.NS', 'HINDALCO.NS', 'JSWSTEEL.NS', 'ADANIENT.NS',
               'APLAPOLLO.NS']
NIFTY100_QUALITY_30 = ['HEROMOTOCO.NS', 'COALINDIA.NS', 'BAJAJ-AUTO.NS', 'MARUTI.NS', 'DIVISLAB.NS', 'EICHERMOT.NS',
                       'BAJFINANCE.NS', 'HDFCAMC.NS', 'HCLTECH.NS', 'COLPAL.NS', 'WIPRO.NS', 'ASIANPAINT.NS',
                       'TECHM.NS', 'BOSCHLTD.NS', 'HAVELLS.NS', 'MUTHOOTFIN.NS', 'DABUR.NS', 'HDFCBANK.NS',
                       'NESTLEIND.NS', 'MARICO.NS', 'HAL.NS', 'TCS.NS', 'LTIM.NS', 'GODREJCP.NS', 'BRITANNIA.NS',
                       'BERGEPAINT.NS', 'HINDUNILVR.NS', 'ITC.NS', 'PIDILITIND.NS', 'INFY.NS']
NIFTY50_VALUE_20 = ['HEROMOTOCO.NS', 'COALINDIA.NS', 'BAJAJ-AUTO.NS', 'ONGC.NS', 'UPL.NS', 'NTPC.NS', 'HCLTECH.NS',
                    'WIPRO.NS', 'TECHM.NS', 'TCS.NS', 'TATASTEEL.NS', 'BRITANNIA.NS', 'GRASIM.NS', 'POWERGRID.NS',
                    'HINDALCO.NS', 'JSWSTEEL.NS', 'HINDUNILVR.NS', 'ITC.NS', 'INFY.NS', 'BPCL.NS']
NIFTY_LARGEMIDCAP_250 = ['GMRINFRA.NS', 'IDEA.NS', 'PGHH.NS', 'IRFC.NS', 'CLEAN.NS', 'DMART.NS', 'TTML.NS',
                         'BANDHANBNK.NS', 'JSWENERGY.NS', 'LAURUSLABS.NS', 'MSUMI.NS', 'OIL.NS', 'HAPPSTMNDS.NS',
                         'NAM-INDIA.NS', 'HEROMOTOCO.NS', 'ALKYLAMINE.NS', 'SUNDARMFIN.NS', 'VEDL.NS', 'COALINDIA.NS',
                         'NYKAA.NS', 'ISEC.NS', 'BAJAJ-AUTO.NS', 'POLYCAB.NS', 'AMBUJACEM.NS', 'MARUTI.NS',
                         'CROMPTON.NS', 'VBL.NS', 'ACC.NS', 'GODREJIND.NS', 'YESBANK.NS', 'M&MFIN.NS', 'PFC.NS',
                         'CHOLAFIN.NS', 'SHRIRAMFIN.NS', 'PETRONET.NS', 'AIAENG.NS', 'STARHEALTH.NS', 'PFIZER.NS',
                         'AAVAS.NS', 'FLUOROCHEM.NS', 'DIVISLAB.NS', 'TATAPOWER.NS', 'LICI.NS', 'GICRE.NS', 'NIACL.NS',
                         'L&TFH.NS', 'LTTS.NS', 'UNIONBANK.NS', 'BANKINDIA.NS', 'ONGC.NS', 'ZOMATO.NS', 'HINDZINC.NS',
                         'EICHERMOT.NS', 'BAJFINANCE.NS', 'THERMAX.NS', 'SUNDRMFAST.NS', 'PRESTIGE.NS', 'UPL.NS',
                         'BHARTIARTL.NS', 'PNB.NS', 'NTPC.NS', 'LICHSGFIN.NS', 'AJANTPHARM.NS', 'SONACOMS.NS',
                         'GODREJPROP.NS', 'SCHAEFFLER.NS', 'RECLTD.NS', 'DIXON.NS', 'PATANJALI.NS', 'SAIL.NS',
                         'DEVYANI.NS', 'BAJAJFINSV.NS', 'HDFCAMC.NS', 'ASHOKLEY.NS', 'BIOCON.NS', 'HCLTECH.NS',
                         'DLF.NS', 'FORTIS.NS', 'TATAELXSI.NS', 'GLAND.NS', 'HDFCLIFE.NS', 'M&M.NS', 'TATACONSUM.NS',
                         'SBICARD.NS', 'INDUSINDBK.NS', 'PHOENIXLTD.NS', 'SKFINDIA.NS', 'IDFCFIRSTB.NS', 'FINEORG.NS',
                         'COLPAL.NS', 'CANBK.NS', 'ICICIGI.NS', 'PEL.NS', 'MOTHERSON.NS', 'APOLLOTYRE.NS', 'DRREDDY.NS',
                         'TITAN.NS', 'ICICIBANK.NS', 'TATAMOTORS.NS', 'WIPRO.NS', 'SUNTV.NS', 'AXISBANK.NS',
                         'LALPATHLAB.NS', 'WHIRLPOOL.NS', 'VINATIORGA.NS', 'SIEMENS.NS', 'ZEEL.NS', 'KOTAKBANK.NS',
                         'EMAMILTD.NS', 'BATAINDIA.NS', 'COFORGE.NS', 'TVSMOTOR.NS', 'ABFRL.NS', 'ICICIPRULI.NS',
                         'VOLTAS.NS', 'ABBOTINDIA.NS', 'ASIANPAINT.NS', 'AFFLE.NS', 'UBL.NS', 'KANSAINER.NS',
                         'TRIDENT.NS', 'FEDERALBNK.NS', 'TORNTPHARM.NS', 'TORNTPOWER.NS', 'INDIANB.NS', 'ABB.NS',
                         'INDUSTOWER.NS', 'TATACHEM.NS', 'MRF.NS', 'RAMCOCEM.NS', 'LINDEINDIA.NS', 'COROMANDEL.NS',
                         'AARTIIND.NS', 'SBILIFE.NS', 'SBIN.NS', 'OFSS.NS', 'GAIL.NS', 'GUJGASLTD.NS', 'MFSL.NS',
                         'BAYERCROP.NS', 'TECHM.NS', 'ULTRACEMCO.NS', 'MPHASIS.NS', 'PAYTM.NS', 'TIINDIA.NS', 'NHPC.NS',
                         'SHREECEM.NS', 'BANKBARODA.NS', 'ABCAPITAL.NS', 'LT.NS', 'ASTRAL.NS', 'HONAUT.NS',
                         'AUROPHARMA.NS', 'HDFC.NS', 'BOSCHLTD.NS', 'CONCOR.NS', 'HAVELLS.NS', 'RELAXO.NS',
                         'DALBHARAT.NS', 'LUPIN.NS', 'MUTHOOTFIN.NS', 'ZYDUSLIFE.NS', 'KPRMILL.NS', 'KAJARIACER.NS',
                         'TIMKEN.NS', 'DABUR.NS', 'HDFCBANK.NS', 'JINDALSTEL.NS', 'OBEROIRLTY.NS', 'NMDC.NS',
                         'RELIANCE.NS', 'SUPREMEIND.NS', 'IPCALAB.NS', 'NESTLEIND.NS', 'BHARATFORG.NS', 'SUMICHEM.NS',
                         'MARICO.NS', 'METROBRAND.NS', 'TATACOMM.NS', 'IRCTC.NS', 'HAL.NS', 'TCS.NS', 'RAJESHEXPO.NS',
                         'BALKRISIND.NS', 'POONAWALLA.NS', 'CRISIL.NS', 'LTIM.NS', 'BHEL.NS', 'IOC.NS', 'PAGEIND.NS',
                         'GODREJCP.NS', 'SUNPHARMA.NS', 'TATASTEEL.NS', 'ALKEM.NS', 'ADANIPORTS.NS', 'MANYAVAR.NS',
                         'BRITANNIA.NS', 'GRASIM.NS', 'POWERGRID.NS', 'MCDOWELL-N.NS', 'INDIGO.NS', 'JKCEMENT.NS',
                         'ATUL.NS', 'BEL.NS', 'BERGEPAINT.NS', 'HINDALCO.NS', 'ENDURANCE.NS', 'ADANIPOWER.NS',
                         'INDHOTEL.NS', 'JSWSTEEL.NS', 'JUBLFOOD.NS', 'GRINDWELL.NS', 'HINDUNILVR.NS', 'BLUEDART.NS',
                         'NAUKRI.NS', 'CIPLA.NS', 'ESCORTS.NS', 'DELHIVERY.NS', 'ITC.NS', 'CGPOWER.NS', 'NAVINFLUOR.NS',
                         '3MINDIA.NS', 'PIDILITIND.NS', 'INFY.NS', 'SYNGENE.NS', 'CUMMINSIND.NS', 'SOLARINDS.NS',
                         'TRENT.NS', 'BAJAJHLDNG.NS', 'PERSISTENT.NS', 'IGL.NS', 'LODHA.NS', 'ZFCVINDIA.NS', 'PIIND.NS',
                         'APOLLOHOSP.NS', 'DEEPAKNTR.NS', 'ADANIENT.NS', 'SRF.NS', 'MAXHEALTH.NS', 'APLAPOLLO.NS',
                         'ATGL.NS', 'POLICYBZR.NS', 'AUBANK.NS', 'AWL.NS', 'GLAXO.NS', 'UNOMINDA.NS', 'BPCL.NS',
                         'HINDPETRO.NS', 'ADANIGREEN.NS', 'ADANITRANS.NS']
NIFTY_MIDCAP_150 = ['GMRINFRA.NS', 'IDEA.NS', 'IRFC.NS', 'CLEAN.NS', 'TTML.NS', 'BANDHANBNK.NS', 'JSWENERGY.NS',
                    'LAURUSLABS.NS', 'MSUMI.NS', 'OIL.NS', 'HAPPSTMNDS.NS', 'NAM-INDIA.NS', 'ALKYLAMINE.NS',
                    'SUNDARMFIN.NS', 'ISEC.NS', 'POLYCAB.NS', 'CROMPTON.NS', 'GODREJIND.NS', 'YESBANK.NS', 'M&MFIN.NS',
                    'PFC.NS', 'SHRIRAMFIN.NS', 'PETRONET.NS', 'AIAENG.NS', 'STARHEALTH.NS', 'PFIZER.NS', 'AAVAS.NS',
                    'FLUOROCHEM.NS', 'GICRE.NS', 'NIACL.NS', 'L&TFH.NS', 'LTTS.NS', 'UNIONBANK.NS', 'BANKINDIA.NS',
                    'HINDZINC.NS', 'THERMAX.NS', 'SUNDRMFAST.NS', 'PRESTIGE.NS', 'PNB.NS', 'LICHSGFIN.NS',
                    'AJANTPHARM.NS', 'SONACOMS.NS', 'GODREJPROP.NS', 'SCHAEFFLER.NS', 'RECLTD.NS', 'DIXON.NS',
                    'PATANJALI.NS', 'SAIL.NS', 'DEVYANI.NS', 'ASHOKLEY.NS', 'BIOCON.NS', 'FORTIS.NS', 'TATAELXSI.NS',
                    'GLAND.NS', 'PHOENIXLTD.NS', 'SKFINDIA.NS', 'IDFCFIRSTB.NS', 'FINEORG.NS', 'PEL.NS',
                    'APOLLOTYRE.NS', 'SUNTV.NS', 'LALPATHLAB.NS', 'WHIRLPOOL.NS', 'VINATIORGA.NS', 'ZEEL.NS',
                    'EMAMILTD.NS', 'BATAINDIA.NS', 'COFORGE.NS', 'TVSMOTOR.NS', 'ABFRL.NS', 'VOLTAS.NS',
                    'ABBOTINDIA.NS', 'AFFLE.NS', 'UBL.NS', 'KANSAINER.NS', 'TRIDENT.NS', 'FEDERALBNK.NS',
                    'TORNTPOWER.NS', 'INDIANB.NS', 'TATACHEM.NS', 'MRF.NS', 'RAMCOCEM.NS', 'LINDEINDIA.NS',
                    'COROMANDEL.NS', 'AARTIIND.NS', 'OFSS.NS', 'GUJGASLTD.NS', 'MFSL.NS', 'BAYERCROP.NS', 'MPHASIS.NS',
                    'PAYTM.NS', 'TIINDIA.NS', 'NHPC.NS', 'ABCAPITAL.NS', 'ASTRAL.NS', 'HONAUT.NS', 'AUROPHARMA.NS',
                    'CONCOR.NS', 'RELAXO.NS', 'DALBHARAT.NS', 'LUPIN.NS', 'ZYDUSLIFE.NS', 'KPRMILL.NS', 'KAJARIACER.NS',
                    'TIMKEN.NS', 'JINDALSTEL.NS', 'OBEROIRLTY.NS', 'NMDC.NS', 'SUPREMEIND.NS', 'IPCALAB.NS',
                    'BHARATFORG.NS', 'SUMICHEM.NS', 'METROBRAND.NS', 'TATACOMM.NS', 'RAJESHEXPO.NS', 'BALKRISIND.NS',
                    'POONAWALLA.NS', 'CRISIL.NS', 'BHEL.NS', 'ALKEM.NS', 'MANYAVAR.NS', 'JKCEMENT.NS', 'ATUL.NS',
                    'ENDURANCE.NS', 'ADANIPOWER.NS', 'INDHOTEL.NS', 'JUBLFOOD.NS', 'GRINDWELL.NS', 'BLUEDART.NS',
                    'ESCORTS.NS', 'DELHIVERY.NS', 'CGPOWER.NS', 'NAVINFLUOR.NS', '3MINDIA.NS', 'SYNGENE.NS',
                    'CUMMINSIND.NS', 'SOLARINDS.NS', 'TRENT.NS', 'PERSISTENT.NS', 'IGL.NS', 'LODHA.NS', 'ZFCVINDIA.NS',
                    'DEEPAKNTR.NS', 'MAXHEALTH.NS', 'APLAPOLLO.NS', 'POLICYBZR.NS', 'AUBANK.NS', 'GLAXO.NS',
                    'UNOMINDA.NS', 'HINDPETRO.NS']
NIFTY_MNC = ['PGHH.NS', 'VEDL.NS', 'AMBUJACEM.NS', 'MARUTI.NS', 'PFIZER.NS', 'SCHAEFFLER.NS', 'ASHOKLEY.NS', 'GLAND.NS',
             'SKFINDIA.NS', 'SANOFI.NS', 'COLPAL.NS', 'SIEMENS.NS', 'BATAINDIA.NS', 'ABBOTINDIA.NS', 'UBL.NS',
             'KANSAINER.NS', 'ABB.NS', 'OFSS.NS', 'MPHASIS.NS', 'HONAUT.NS', 'BOSCHLTD.NS', 'NESTLEIND.NS', 'CRISIL.NS',
             'BRITANNIA.NS', 'MCDOWELL-N.NS', 'GRINDWELL.NS', 'HINDUNILVR.NS', '3MINDIA.NS', 'CUMMINSIND.NS',
             'GLAXO.NS']
NIFTY_100 = ['PGHH.NS', 'DMART.NS', 'HEROMOTOCO.NS', 'VEDL.NS', 'COALINDIA.NS', 'NYKAA.NS', 'BAJAJ-AUTO.NS',
             'AMBUJACEM.NS', 'MARUTI.NS', 'VBL.NS', 'ACC.NS', 'CHOLAFIN.NS', 'DIVISLAB.NS', 'TATAPOWER.NS', 'LICI.NS',
             'ONGC.NS', 'ZOMATO.NS', 'EICHERMOT.NS', 'BAJFINANCE.NS', 'UPL.NS', 'BHARTIARTL.NS', 'NTPC.NS',
             'BAJAJFINSV.NS', 'HDFCAMC.NS', 'HCLTECH.NS', 'DLF.NS', 'HDFCLIFE.NS', 'M&M.NS', 'TATACONSUM.NS',
             'SBICARD.NS', 'INDUSINDBK.NS', 'COLPAL.NS', 'CANBK.NS', 'ICICIGI.NS', 'MOTHERSON.NS', 'DRREDDY.NS',
             'TITAN.NS', 'ICICIBANK.NS', 'TATAMOTORS.NS', 'WIPRO.NS', 'AXISBANK.NS', 'SIEMENS.NS', 'KOTAKBANK.NS',
             'ICICIPRULI.NS', 'ASIANPAINT.NS', 'TORNTPHARM.NS', 'ABB.NS', 'INDUSTOWER.NS', 'SBILIFE.NS', 'SBIN.NS',
             'GAIL.NS', 'TECHM.NS', 'ULTRACEMCO.NS', 'SHREECEM.NS', 'BANKBARODA.NS', 'LT.NS', 'HDFC.NS', 'BOSCHLTD.NS',
             'HAVELLS.NS', 'MUTHOOTFIN.NS', 'DABUR.NS', 'HDFCBANK.NS', 'RELIANCE.NS', 'NESTLEIND.NS', 'MARICO.NS',
             'IRCTC.NS', 'HAL.NS', 'TCS.NS', 'LTIM.NS', 'IOC.NS', 'PAGEIND.NS', 'GODREJCP.NS', 'SUNPHARMA.NS',
             'TATASTEEL.NS', 'ADANIPORTS.NS', 'BRITANNIA.NS', 'GRASIM.NS', 'POWERGRID.NS', 'MCDOWELL-N.NS', 'INDIGO.NS',
             'BEL.NS', 'BERGEPAINT.NS', 'HINDALCO.NS', 'JSWSTEEL.NS', 'HINDUNILVR.NS', 'NAUKRI.NS', 'CIPLA.NS',
             'ITC.NS', 'PIDILITIND.NS', 'INFY.NS', 'BAJAJHLDNG.NS', 'PIIND.NS', 'APOLLOHOSP.NS', 'ADANIENT.NS',
             'SRF.NS', 'ATGL.NS', 'AWL.NS', 'BPCL.NS', 'ADANIGREEN.NS', 'ADANITRANS.NS']
NIFTY_COMMODITIES = ['VEDL.NS', 'COALINDIA.NS', 'AMBUJACEM.NS', 'ACC.NS', 'TATAPOWER.NS', 'ONGC.NS', 'UPL.NS',
                     'NTPC.NS', 'SAIL.NS', 'TATACHEM.NS', 'ULTRACEMCO.NS', 'SHREECEM.NS', 'DALBHARAT.NS',
                     'JINDALSTEL.NS', 'RELIANCE.NS', 'IOC.NS', 'TATASTEEL.NS', 'GRASIM.NS', 'ATUL.NS', 'HINDALCO.NS',
                     'ADANIPOWER.NS', 'JSWSTEEL.NS', 'NAVINFLUOR.NS', 'PIDILITIND.NS', 'PIIND.NS', 'DEEPAKNTR.NS',
                     'SRF.NS', 'BPCL.NS', 'HINDPETRO.NS', 'ADANIGREEN.NS']
NIFTY100_ESG = ['PGHH.NS', 'DMART.NS', 'BANDHANBNK.NS', 'HEROMOTOCO.NS', 'COALINDIA.NS', 'NYKAA.NS', 'BAJAJ-AUTO.NS',
                'AMBUJACEM.NS', 'MARUTI.NS', 'ACC.NS', 'CHOLAFIN.NS', 'DIVISLAB.NS', 'TATAPOWER.NS', 'LICI.NS',
                'ZOMATO.NS', 'EICHERMOT.NS', 'BAJFINANCE.NS', 'BHARTIARTL.NS', 'BAJAJFINSV.NS', 'HDFCAMC.NS',
                'BIOCON.NS', 'HCLTECH.NS', 'DLF.NS', 'GLAND.NS', 'HDFCLIFE.NS', 'M&M.NS', 'TATACONSUM.NS', 'SBICARD.NS',
                'INDUSINDBK.NS', 'COLPAL.NS', 'ICICIGI.NS', 'MOTHERSON.NS', 'DRREDDY.NS', 'TITAN.NS', 'ICICIBANK.NS',
                'TATAMOTORS.NS', 'WIPRO.NS', 'AXISBANK.NS', 'SIEMENS.NS', 'KOTAKBANK.NS', 'ICICIPRULI.NS',
                'ASIANPAINT.NS', 'TORNTPHARM.NS', 'INDUSTOWER.NS', 'SBILIFE.NS', 'SBIN.NS', 'GAIL.NS', 'TECHM.NS',
                'ULTRACEMCO.NS', 'MPHASIS.NS', 'PAYTM.NS', 'SHREECEM.NS', 'LT.NS', 'HDFC.NS', 'BOSCHLTD.NS',
                'HAVELLS.NS', 'MUTHOOTFIN.NS', 'DABUR.NS', 'HDFCBANK.NS', 'RELIANCE.NS', 'NESTLEIND.NS', 'MARICO.NS',
                'IRCTC.NS', 'TCS.NS', 'LTIM.NS', 'IOC.NS', 'GODREJCP.NS', 'SUNPHARMA.NS', 'TATASTEEL.NS',
                'BRITANNIA.NS', 'GRASIM.NS', 'POWERGRID.NS', 'INDIGO.NS', 'BERGEPAINT.NS', 'HINDALCO.NS', 'JSWSTEEL.NS',
                'HINDUNILVR.NS', 'NAUKRI.NS', 'CIPLA.NS', 'PIDILITIND.NS', 'INFY.NS', 'BAJAJHLDNG.NS', 'PIIND.NS',
                'APOLLOHOSP.NS', 'SRF.NS', 'ATGL.NS', 'BPCL.NS', 'ADANIGREEN.NS', 'ADANITRANS.NS']
NIFTY_MIDCAP_SELECT = ['BANDHANBNK.NS', 'LAURUSLABS.NS', 'SHRIRAMFIN.NS', 'PNB.NS', 'GODREJPROP.NS', 'ASHOKLEY.NS',
                       'IDFCFIRSTB.NS', 'TVSMOTOR.NS', 'VOLTAS.NS', 'FEDERALBNK.NS', 'MRF.NS', 'MPHASIS.NS',
                       'ASTRAL.NS', 'AUROPHARMA.NS', 'CONCOR.NS', 'JINDALSTEL.NS', 'BHARATFORG.NS', 'BALKRISIND.NS',
                       'INDHOTEL.NS', 'JUBLFOOD.NS', 'CUMMINSIND.NS', 'TRENT.NS', 'PERSISTENT.NS', 'AUBANK.NS',
                       'HINDPETRO.NS']
NIFTY_FMCG = ['PGHH.NS', 'VBL.NS', 'TATACONSUM.NS', 'COLPAL.NS', 'EMAMILTD.NS', 'UBL.NS', 'DABUR.NS', 'NESTLEIND.NS',
              'MARICO.NS', 'GODREJCP.NS', 'BRITANNIA.NS', 'MCDOWELL-N.NS', 'HINDUNILVR.NS', 'ITC.NS', 'RADICO.NS']
NIFTY_PHARMA = ['LAURUSLABS.NS', 'GLENMARK.NS', 'NATCOPHARM.NS', 'GRANULES.NS', 'PFIZER.NS', 'DIVISLAB.NS', 'BIOCON.NS',
                'GLAND.NS', 'SANOFI.NS', 'DRREDDY.NS', 'ABBOTINDIA.NS', 'TORNTPHARM.NS', 'AUROPHARMA.NS', 'LUPIN.NS',
                'ZYDUSLIFE.NS', 'IPCALAB.NS', 'SUNPHARMA.NS', 'ALKEM.NS', 'CIPLA.NS', 'GLAXO.NS']
NIFTY_REALTY = ['IBREALEST.NS', 'PRESTIGE.NS', 'GODREJPROP.NS', 'MAHLIFE.NS', 'DLF.NS', 'PHOENIXLTD.NS', 'SOBHA.NS',
                'BRIGADE.NS', 'OBEROIRLTY.NS', 'LODHA.NS']
NIFTY100_EQUAL_WEIGHT = ['PGHH.NS', 'DMART.NS', 'HEROMOTOCO.NS', 'VEDL.NS', 'COALINDIA.NS', 'NYKAA.NS', 'BAJAJ-AUTO.NS',
                         'AMBUJACEM.NS', 'MARUTI.NS', 'VBL.NS', 'ACC.NS', 'CHOLAFIN.NS', 'DIVISLAB.NS', 'TATAPOWER.NS',
                         'LICI.NS', 'ONGC.NS', 'ZOMATO.NS', 'EICHERMOT.NS', 'BAJFINANCE.NS', 'UPL.NS', 'BHARTIARTL.NS',
                         'NTPC.NS', 'BAJAJFINSV.NS', 'HDFCAMC.NS', 'HCLTECH.NS', 'DLF.NS', 'HDFCLIFE.NS', 'M&M.NS',
                         'TATACONSUM.NS', 'SBICARD.NS', 'INDUSINDBK.NS', 'COLPAL.NS', 'CANBK.NS', 'ICICIGI.NS',
                         'MOTHERSON.NS', 'DRREDDY.NS', 'TITAN.NS', 'ICICIBANK.NS', 'TATAMOTORS.NS', 'WIPRO.NS',
                         'AXISBANK.NS', 'SIEMENS.NS', 'KOTAKBANK.NS', 'ICICIPRULI.NS', 'ASIANPAINT.NS', 'TORNTPHARM.NS',
                         'ABB.NS', 'INDUSTOWER.NS', 'SBILIFE.NS', 'SBIN.NS', 'GAIL.NS', 'TECHM.NS', 'ULTRACEMCO.NS',
                         'SHREECEM.NS', 'BANKBARODA.NS', 'LT.NS', 'HDFC.NS', 'BOSCHLTD.NS', 'HAVELLS.NS',
                         'MUTHOOTFIN.NS', 'DABUR.NS', 'HDFCBANK.NS', 'RELIANCE.NS', 'NESTLEIND.NS', 'MARICO.NS',
                         'IRCTC.NS', 'HAL.NS', 'TCS.NS', 'LTIM.NS', 'IOC.NS', 'PAGEIND.NS', 'GODREJCP.NS',
                         'SUNPHARMA.NS', 'TATASTEEL.NS', 'ADANIPORTS.NS', 'BRITANNIA.NS', 'GRASIM.NS', 'POWERGRID.NS',
                         'MCDOWELL-N.NS', 'INDIGO.NS', 'BEL.NS', 'BERGEPAINT.NS', 'HINDALCO.NS', 'JSWSTEEL.NS',
                         'HINDUNILVR.NS', 'NAUKRI.NS', 'CIPLA.NS', 'ITC.NS', 'PIDILITIND.NS', 'INFY.NS',
                         'BAJAJHLDNG.NS', 'PIIND.NS', 'APOLLOHOSP.NS', 'ADANIENT.NS', 'SRF.NS', 'ATGL.NS', 'AWL.NS',
                         'BPCL.NS', 'ADANIGREEN.NS', 'ADANITRANS.NS']
NIFTY_200 = ['IDEA.NS', 'PGHH.NS', 'IRFC.NS', 'DMART.NS', 'TTML.NS', 'BANDHANBNK.NS', 'JSWENERGY.NS', 'LAURUSLABS.NS',
             'MSUMI.NS', 'OIL.NS', 'HEROMOTOCO.NS', 'VEDL.NS', 'COALINDIA.NS', 'NYKAA.NS', 'BAJAJ-AUTO.NS',
             'POLYCAB.NS', 'AMBUJACEM.NS', 'MARUTI.NS', 'CROMPTON.NS', 'VBL.NS', 'ACC.NS', 'YESBANK.NS', 'M&MFIN.NS',
             'PFC.NS', 'CHOLAFIN.NS', 'SHRIRAMFIN.NS', 'PETRONET.NS', 'FLUOROCHEM.NS', 'DIVISLAB.NS', 'TATAPOWER.NS',
             'LICI.NS', 'L&TFH.NS', 'LTTS.NS', 'UNIONBANK.NS', 'BANKINDIA.NS', 'ONGC.NS', 'ZOMATO.NS', 'HINDZINC.NS',
             'EICHERMOT.NS', 'BAJFINANCE.NS', 'PRESTIGE.NS', 'UPL.NS', 'BHARTIARTL.NS', 'PNB.NS', 'NTPC.NS',
             'LICHSGFIN.NS', 'SONACOMS.NS', 'GODREJPROP.NS', 'RECLTD.NS', 'DIXON.NS', 'PATANJALI.NS', 'SAIL.NS',
             'DEVYANI.NS', 'BAJAJFINSV.NS', 'HDFCAMC.NS', 'ASHOKLEY.NS', 'BIOCON.NS', 'HCLTECH.NS', 'DLF.NS',
             'FORTIS.NS', 'TATAELXSI.NS', 'GLAND.NS', 'HDFCLIFE.NS', 'M&M.NS', 'TATACONSUM.NS', 'SBICARD.NS',
             'INDUSINDBK.NS', 'IDFCFIRSTB.NS', 'COLPAL.NS', 'CANBK.NS', 'ICICIGI.NS', 'PEL.NS', 'MOTHERSON.NS',
             'APOLLOTYRE.NS', 'DRREDDY.NS', 'TITAN.NS', 'ICICIBANK.NS', 'TATAMOTORS.NS', 'WIPRO.NS', 'SUNTV.NS',
             'AXISBANK.NS', 'LALPATHLAB.NS', 'WHIRLPOOL.NS', 'SIEMENS.NS', 'ZEEL.NS', 'KOTAKBANK.NS', 'BATAINDIA.NS',
             'COFORGE.NS', 'TVSMOTOR.NS', 'ABFRL.NS', 'ICICIPRULI.NS', 'VOLTAS.NS', 'ABBOTINDIA.NS', 'ASIANPAINT.NS',
             'UBL.NS', 'TRIDENT.NS', 'FEDERALBNK.NS', 'TORNTPHARM.NS', 'TORNTPOWER.NS', 'INDIANB.NS', 'ABB.NS',
             'INDUSTOWER.NS', 'TATACHEM.NS', 'MRF.NS', 'RAMCOCEM.NS', 'COROMANDEL.NS', 'SBILIFE.NS', 'SBIN.NS',
             'OFSS.NS', 'GAIL.NS', 'GUJGASLTD.NS', 'MFSL.NS', 'TECHM.NS', 'ULTRACEMCO.NS', 'MPHASIS.NS', 'PAYTM.NS',
             'TIINDIA.NS', 'NHPC.NS', 'SHREECEM.NS', 'BANKBARODA.NS', 'ABCAPITAL.NS', 'LT.NS', 'ASTRAL.NS', 'HONAUT.NS',
             'AUROPHARMA.NS', 'HDFC.NS', 'BOSCHLTD.NS', 'CONCOR.NS', 'HAVELLS.NS', 'DALBHARAT.NS', 'LUPIN.NS',
             'MUTHOOTFIN.NS', 'ZYDUSLIFE.NS', 'DABUR.NS', 'HDFCBANK.NS', 'JINDALSTEL.NS', 'OBEROIRLTY.NS',
             'RELIANCE.NS', 'NMDC.NS', 'IPCALAB.NS', 'NESTLEIND.NS', 'BHARATFORG.NS', 'MARICO.NS', 'TATACOMM.NS',
             'IRCTC.NS', 'HAL.NS', 'TCS.NS', 'BALKRISIND.NS', 'POONAWALLA.NS', 'LTIM.NS', 'BHEL.NS', 'IOC.NS',
             'PAGEIND.NS', 'GODREJCP.NS', 'SUNPHARMA.NS', 'TATASTEEL.NS', 'ALKEM.NS', 'ADANIPORTS.NS', 'BRITANNIA.NS',
             'GRASIM.NS', 'POWERGRID.NS', 'MCDOWELL-N.NS', 'INDIGO.NS', 'BEL.NS', 'BERGEPAINT.NS', 'HINDALCO.NS',
             'ADANIPOWER.NS', 'INDHOTEL.NS', 'JSWSTEEL.NS', 'JUBLFOOD.NS', 'HINDUNILVR.NS', 'NAUKRI.NS', 'CIPLA.NS',
             'ESCORTS.NS', 'DELHIVERY.NS', 'ITC.NS', 'CGPOWER.NS', 'NAVINFLUOR.NS', 'PIDILITIND.NS', 'INFY.NS',
             'SYNGENE.NS', 'CUMMINSIND.NS', 'TRENT.NS', 'BAJAJHLDNG.NS', 'PERSISTENT.NS', 'IGL.NS', 'PIIND.NS',
             'APOLLOHOSP.NS', 'DEEPAKNTR.NS', 'ADANIENT.NS', 'SRF.NS', 'MAXHEALTH.NS', 'ATGL.NS', 'POLICYBZR.NS',
             'AUBANK.NS', 'AWL.NS', 'BPCL.NS', 'HINDPETRO.NS', 'ADANIGREEN.NS', 'ADANITRANS.NS']
NIFTY100_LOW_VOLATILITY_30 = ['HEROMOTOCO.NS', 'BAJAJ-AUTO.NS', 'NTPC.NS', 'HCLTECH.NS', 'HDFCLIFE.NS', 'COLPAL.NS',
                              'DRREDDY.NS', 'WIPRO.NS', 'KOTAKBANK.NS', 'ASIANPAINT.NS', 'SBILIFE.NS', 'TECHM.NS',
                              'ULTRACEMCO.NS', 'LT.NS', 'DABUR.NS', 'HDFCBANK.NS', 'RELIANCE.NS', 'NESTLEIND.NS',
                              'MARICO.NS', 'TCS.NS', 'IOC.NS', 'SUNPHARMA.NS', 'BRITANNIA.NS', 'POWERGRID.NS',
                              'BERGEPAINT.NS', 'HINDUNILVR.NS', 'CIPLA.NS', 'ITC.NS', 'PIDILITIND.NS', 'INFY.NS']
NIFTY_BANK = ['NIFTY BANK.NS', 'BANDHANBNK.NS', 'PNB.NS', 'INDUSINDBK.NS', 'IDFCFIRSTB.NS', 'ICICIBANK.NS',
              'AXISBANK.NS', 'KOTAKBANK.NS', 'FEDERALBNK.NS', 'SBIN.NS', 'BANKBARODA.NS', 'HDFCBANK.NS', 'AUBANK.NS']
NIFTY_MIDCAP_LIQUID_15 = ['BANDHANBNK.NS', 'SHRIRAMFIN.NS', 'GODREJPROP.NS', 'ASHOKLEY.NS', 'ZEEL.NS', 'TVSMOTOR.NS',
                          'VOLTAS.NS', 'FEDERALBNK.NS', 'AUROPHARMA.NS', 'CONCOR.NS', 'JINDALSTEL.NS', 'BHARATFORG.NS',
                          'INDHOTEL.NS', 'JUBLFOOD.NS', 'PERSISTENT.NS']
NIFTY_CPSE = ['OIL.NS', 'COALINDIA.NS', 'ONGC.NS', 'NTPC.NS', 'COCHINSHIP.NS', 'NBCC.NS', 'NHPC.NS', 'NLCINDIA.NS',
              'POWERGRID.NS', 'BEL.NS', 'SJVN.NS']
NIFTY_FINANCIAL_SERVICES = ['IEX.NS', 'PFC.NS', 'CHOLAFIN.NS', 'SHRIRAMFIN.NS', 'BAJFINANCE.NS', 'RECLTD.NS',
                            'BAJAJFINSV.NS', 'HDFCAMC.NS', 'HDFCLIFE.NS', 'SBICARD.NS', 'ICICIGI.NS', 'ICICIBANK.NS',
                            'AXISBANK.NS', 'KOTAKBANK.NS', 'ICICIPRULI.NS', 'SBILIFE.NS', 'SBIN.NS', 'HDFC.NS',
                            'MUTHOOTFIN.NS', 'HDFCBANK.NS']
NIFTY_MIDSMALLCAP_400 = ['RVNL.NS', 'BCG.NS', 'JBMA.NS', 'LXCHEM.NS', 'VAIBHAVGBL.NS', 'BALAMINES.NS', 'TANLA.NS',
                         'UCOBANK.NS', 'GMRINFRA.NS', 'PNBHOUSING.NS', 'POLYPLEX.NS', 'GUJALKALI.NS', 'RTNINDIA.NS',
                         'PPLPHARMA.NS', 'IDEA.NS', 'WELSPUNIND.NS', 'AVANTIFEED.NS', 'INDIGOPNTS.NS', 'CAMS.NS',
                         'TCNSBRANDS.NS', 'GRAPHITE.NS', 'IRFC.NS', 'TEJASNET.NS', 'FACT.NS', 'CLEAN.NS', 'OLECTRA.NS',
                         'TTML.NS', 'IEX.NS', 'PRSMJOHNSN.NS', 'MAHABANK.NS', 'JUBLPHARMA.NS', 'STLTECH.NS',
                         'EASEMYTRIP.NS', 'LUXIND.NS', 'BANDHANBNK.NS', 'LATENTVIEW.NS', 'JSWENERGY.NS', 'BSE.NS',
                         'HEG.NS', 'LAURUSLABS.NS', 'MSUMI.NS', 'KSB.NS', 'SHYAMMETL.NS', 'DELTACORP.NS',
                         'TV18BRDCST.NS', 'APARINDS.NS', 'IBREALEST.NS', 'DATAPATTNS.NS', 'OIL.NS', 'EDELWEISS.NS',
                         'DEEPAKFERT.NS', 'HAPPSTMNDS.NS', 'GNFC.NS', 'CENTURYTEX.NS', 'NETWORK18.NS', 'IOB.NS',
                         'IDBI.NS', 'SUNTECK.NS', 'NAM-INDIA.NS', 'GRINFRA.NS', 'RENUKA.NS', 'GODREJAGRO.NS',
                         'HUDCO.NS', 'CHEMPLASTS.NS', 'INTELLECT.NS', 'MHRIL.NS', 'CSBBANK.NS', 'ALKYLAMINE.NS',
                         'JUBLINGREA.NS', 'WELCORP.NS', 'BALRAMCHIN.NS', 'CENTRALBK.NS', 'SUNDARMFIN.NS',
                         'MAHINDCIE.NS', 'MOTILALOFS.NS', 'GALAXYSURF.NS', 'TRIVENI.NS', 'JMFINANCIL.NS', 'SUZLON.NS',
                         'RCF.NS', 'VTL.NS', 'CANFINHOME.NS', 'CHAMBLFERT.NS', 'SONATSOFTW.NS', 'MMTC.NS',
                         'GLENMARK.NS', 'ISEC.NS', 'NATCOPHARM.NS', 'SWSOLAR.NS', 'BORORENEW.NS', 'INGERRAND.NS',
                         'POLYCAB.NS', 'MRPL.NS', 'RBA.NS', 'RAIN.NS', 'HLEGLAS.NS', 'CDSL.NS', 'VARROC.NS', 'BBTC.NS',
                         'CROMPTON.NS', 'BSOFT.NS', 'GODREJIND.NS', 'EIDPARRY.NS', 'YESBANK.NS', 'M&MFIN.NS', 'PFC.NS',
                         'PRINCEPIPE.NS', 'SHRIRAMFIN.NS', 'DCMSHRIRAM.NS', 'CESC.NS', 'PETRONET.NS', 'BIRLACORPN.NS',
                         'UFLEX.NS', 'RBLBANK.NS', 'GRANULES.NS', 'AIAENG.NS', 'STARHEALTH.NS', 'PFIZER.NS', 'AAVAS.NS',
                         'GSFC.NS', 'IBULHSGFIN.NS', 'FLUOROCHEM.NS', 'MAHLOG.NS', 'GICRE.NS', 'TCIEXP.NS',
                         'KFINTECH.NS', 'NIACL.NS', 'L&TFH.NS', 'CCL.NS', 'LTTS.NS', 'UNIONBANK.NS', 'FDC.NS', 'CUB.NS',
                         'RALLIS.NS', 'TTKPRESTIG.NS', 'BANKINDIA.NS', 'SHARDACROP.NS', 'MAPMYINDIA.NS',
                         'TATAINVEST.NS', 'HINDZINC.NS', 'FIVESTAR.NS', 'THERMAX.NS', 'EQUITASBNK.NS', 'SUNDRMFAST.NS',
                         'PRESTIGE.NS', 'HIKAL.NS', 'JAMNAAUTO.NS', 'ASAHIINDIA.NS', 'JINDWORLD.NS', 'MFL.NS', 'PNB.NS',
                         'LICHSGFIN.NS', 'ECLERX.NS', 'AJANTPHARM.NS', 'SONACOMS.NS', 'GODREJPROP.NS', 'AMARAJABAT.NS',
                         'COCHINSHIP.NS', 'NUVOCO.NS', 'SCHAEFFLER.NS', 'MTARTECH.NS', 'REDINGTON.NS', 'HINDCOPPER.NS',
                         'ENGINERSIN.NS', 'CASTROLIND.NS', 'UTIAMC.NS', 'ITI.NS', 'RECLTD.NS', 'ASTERDM.NS', 'DIXON.NS',
                         'NATIONALUM.NS', 'AMBER.NS', 'PATANJALI.NS', 'SAIL.NS', 'DEVYANI.NS', 'MAHLIFE.NS',
                         'VGUARD.NS', 'ASHOKLEY.NS', 'BIOCON.NS', 'JKLAKSHMI.NS', 'GREENPANEL.NS', 'WESTLIFE.NS',
                         'FORTIS.NS', 'TATAELXSI.NS', 'EXIDEIND.NS', 'QUESS.NS', 'GLAND.NS', 'HFCL.NS', 'GAEL.NS',
                         'AARTIDRUGS.NS', 'VIJAYA.NS', 'INFIBEAM.NS', 'KRBL.NS', 'PHOENIXLTD.NS', 'SKFINDIA.NS',
                         'SANOFI.NS', 'NCC.NS', 'IDFC.NS', 'IFBIND.NS', 'MANAPPURAM.NS', 'RITES.NS', 'IDFCFIRSTB.NS',
                         'FINEORG.NS', 'PEL.NS', 'CARBORUNIV.NS', 'INDIACEM.NS', 'NOCIL.NS', 'SOBHA.NS',
                         'APOLLOTYRE.NS', 'JKPAPER.NS', 'FINPIPE.NS', 'GPPL.NS', 'SUNTV.NS', 'RAINBOW.NS',
                         'ZENSARTECH.NS', 'LALPATHLAB.NS', 'WHIRLPOOL.NS', 'VINATIORGA.NS', 'BEML.NS', 'ZEEL.NS',
                         'NBCC.NS', 'SUPRAJIT.NS', 'BRIGADE.NS', 'EMAMILTD.NS', 'BATAINDIA.NS', 'COFORGE.NS',
                         'NAZARA.NS', 'TVSMOTOR.NS', 'ABFRL.NS', 'VOLTAS.NS', 'ZYDUSWELL.NS', 'ROSSARI.NS',
                         'ABBOTINDIA.NS', 'AFFLE.NS', 'UBL.NS', 'VMART.NS', 'KENNAMET.NS', 'KANSAINER.NS',
                         'METROPOLIS.NS', 'CREDITACC.NS', 'TRIDENT.NS', 'FEDERALBNK.NS', 'KNRCON.NS', 'TORNTPOWER.NS',
                         'INDIANB.NS', 'TATACHEM.NS', 'BLUESTARCO.NS', 'MRF.NS', 'FINCABLES.NS', 'RAMCOCEM.NS',
                         'VIPIND.NS', 'RATNAMANI.NS', 'LINDEINDIA.NS', 'COROMANDEL.NS', 'AARTIIND.NS', 'ANGELONE.NS',
                         'OFSS.NS', 'GUJGASLTD.NS', 'MFSL.NS', 'BAYERCROP.NS', 'CYIENT.NS', 'GMMPFAUDLR.NS',
                         'MPHASIS.NS', 'PAYTM.NS', 'CERA.NS', 'LEMONTREE.NS', 'PCBL.NS', 'TIINDIA.NS', 'NHPC.NS',
                         'GESHIP.NS', 'ABCAPITAL.NS', 'ASTRAL.NS', 'NLCINDIA.NS', 'KALYANKJIL.NS', 'HONAUT.NS',
                         'AUROPHARMA.NS', 'MAZDOCK.NS', 'CONCOR.NS', 'RELAXO.NS', 'SHOPERSTOP.NS', 'DALBHARAT.NS',
                         'LUPIN.NS', 'ZYDUSLIFE.NS', 'LAXMIMACH.NS', 'KPRMILL.NS', 'KAJARIACER.NS', 'TIMKEN.NS',
                         'CEATLTD.NS', 'KEI.NS', 'JINDALSTEL.NS', 'PRAJIND.NS', 'OBEROIRLTY.NS', 'SUPREMEIND.NS',
                         'NMDC.NS', 'IPCALAB.NS', 'BHARATFORG.NS', 'SUMICHEM.NS', 'METROBRAND.NS', 'SPARC.NS',
                         'INDIAMART.NS', 'TATACOMM.NS', 'BLS.NS', 'BDL.NS', 'CHALET.NS', 'BAJAJELEC.NS',
                         'SWANENERGY.NS', 'RAJESHEXPO.NS', 'BALKRISIND.NS', 'AEGISCHEM.NS', 'POONAWALLA.NS',
                         'CENTURYPLY.NS', 'HGS.NS', 'GARFIBRES.NS', 'CRISIL.NS', 'BHEL.NS', 'JYOTHYLAB.NS',
                         'SUVENPHAR.NS', 'ALKEM.NS', 'MANYAVAR.NS', 'MCX.NS', 'CHOLAHLDNG.NS', 'RHIM.NS', 'JKCEMENT.NS',
                         'ATUL.NS', 'BASF.NS', 'JSL.NS', 'IRB.NS', 'CAMPUS.NS', 'MASTEK.NS', 'TMB.NS', 'EIHOTEL.NS',
                         'FSL.NS', 'APLLTD.NS', 'ELGIEQUIP.NS', 'SJVN.NS', 'ENDURANCE.NS', 'ADANIPOWER.NS',
                         'INDHOTEL.NS', 'GSPL.NS', 'JUBLFOOD.NS', 'PNCINFRA.NS', 'GRINDWELL.NS', 'BLUEDART.NS',
                         'ROUTE.NS', 'KIMS.NS', 'SAPPHIRE.NS', 'ESCORTS.NS', 'DELHIVERY.NS', 'CGPOWER.NS',
                         'NAVINFLUOR.NS', '3MINDIA.NS', 'NH.NS', 'APTUS.NS', 'RADICO.NS', 'POLYMED.NS', 'PVR.NS',
                         'BIKAJI.NS', 'KEC.NS', 'AETHER.NS', 'SYNGENE.NS', 'JBCHEPHARM.NS', 'EPL.NS', 'CUMMINSIND.NS',
                         'TCI.NS', 'POWERINDIA.NS', 'SOLARINDS.NS', 'TRENT.NS', 'TEAMLEASE.NS', 'PERSISTENT.NS',
                         'JUSTDIAL.NS', 'GOCOLORS.NS', 'IGL.NS', 'ACI.NS', 'LODHA.NS', 'ZFCVINDIA.NS', 'DEEPAKNTR.NS',
                         'TRITURBINE.NS', 'RAYMOND.NS', '360ONE.NS', 'MEDPLUS.NS', 'MAXHEALTH.NS', 'APLAPOLLO.NS',
                         'POLICYBZR.NS', 'AUBANK.NS', 'ANURAS.NS', 'GLAXO.NS', 'RUSTOMJEE.NS', 'UNOMINDA.NS', 'IIFL.NS',
                         'GODFRYPHLP.NS', 'KALPATPOWR.NS', 'HOMEFIRST.NS', 'CRAFTSMAN.NS', 'KARURVYSYA.NS',
                         'HINDPETRO.NS', 'MEDANTA.NS', 'ORIENTELEC.NS', 'MGL.NS', 'CGCL.NS', 'KPITTECH.NS']
NIFTY_SMALLCAP_100 = ['RVNL.NS', 'BCG.NS', 'LXCHEM.NS', 'BALAMINES.NS', 'TANLA.NS', 'UCOBANK.NS', 'PNBHOUSING.NS',
                      'PPLPHARMA.NS', 'WELSPUNIND.NS', 'CAMS.NS', 'GRAPHITE.NS', 'TEJASNET.NS', 'FACT.NS', 'IEX.NS',
                      'MAHABANK.NS', 'STLTECH.NS', 'EASEMYTRIP.NS', 'LATENTVIEW.NS', 'BSE.NS', 'TV18BRDCST.NS',
                      'DEEPAKFERT.NS', 'GNFC.NS', 'CENTURYTEX.NS', 'IOB.NS', 'IDBI.NS', 'RENUKA.NS', 'HUDCO.NS',
                      'INTELLECT.NS', 'JUBLINGREA.NS', 'BALRAMCHIN.NS', 'CENTRALBK.NS', 'TRIVENI.NS', 'SUZLON.NS',
                      'VTL.NS', 'CANFINHOME.NS', 'CHAMBLFERT.NS', 'GLENMARK.NS', 'BORORENEW.NS', 'MRPL.NS', 'CDSL.NS',
                      'BSOFT.NS', 'EIDPARRY.NS', 'CESC.NS', 'BIRLACORPN.NS', 'RBLBANK.NS', 'GRANULES.NS', 'CUB.NS',
                      'AMARAJABAT.NS', 'REDINGTON.NS', 'HINDCOPPER.NS', 'UTIAMC.NS', 'NATIONALUM.NS', 'AMBER.NS',
                      'JKLAKSHMI.NS', 'EXIDEIND.NS', 'QUESS.NS', 'HFCL.NS', 'KRBL.NS', 'IDFC.NS', 'MANAPPURAM.NS',
                      'RITES.NS', 'CARBORUNIV.NS', 'INDIACEM.NS', 'NBCC.NS', 'METROPOLIS.NS', 'CREDITACC.NS',
                      'VIPIND.NS', 'ANGELONE.NS', 'CYIENT.NS', 'GMMPFAUDLR.NS', 'NLCINDIA.NS', 'KALYANKJIL.NS',
                      'MAZDOCK.NS', 'KEI.NS', 'PRAJIND.NS', 'INDIAMART.NS', 'BDL.NS', 'BAJAJELEC.NS', 'AEGISCHEM.NS',
                      'MCX.NS', 'JSL.NS', 'IRB.NS', 'CAMPUS.NS', 'FSL.NS', 'ELGIEQUIP.NS', 'ROUTE.NS', 'SAPPHIRE.NS',
                      'RADICO.NS', 'PVR.NS', 'BIKAJI.NS', 'KEC.NS', 'JBCHEPHARM.NS', 'RAYMOND.NS', 'MEDPLUS.NS',
                      'ANURAS.NS', 'IIFL.NS', 'KARURVYSYA.NS', 'MEDANTA.NS', 'MGL.NS', 'KPITTECH.NS']
NIFTY_INDIA_DIGITAL = ['TANLA.NS', 'IDEA.NS', 'HAPPSTMNDS.NS', 'INTELLECT.NS', 'NYKAA.NS', 'SONATSOFTW.NS', 'BSOFT.NS',
                       'LTTS.NS', 'ZOMATO.NS', 'BHARTIARTL.NS', 'HCLTECH.NS', 'TATAELXSI.NS', 'WIPRO.NS', 'COFORGE.NS',
                       'AFFLE.NS', 'OFSS.NS', 'CYIENT.NS', 'TECHM.NS', 'MPHASIS.NS', 'PAYTM.NS', 'INDIAMART.NS',
                       'TATACOMM.NS', 'IRCTC.NS', 'TCS.NS', 'LTIM.NS', 'NAUKRI.NS', 'INFY.NS', 'PERSISTENT.NS',
                       'POLICYBZR.NS', 'KPITTECH.NS']
NIFTY_INFRASTRUCTURE = ['AMBUJACEM.NS', 'ACC.NS', 'PETRONET.NS', 'TATAPOWER.NS', 'ONGC.NS', 'BHARTIARTL.NS', 'NTPC.NS',
                        'GODREJPROP.NS', 'ASHOKLEY.NS', 'DLF.NS', 'SIEMENS.NS', 'INDUSTOWER.NS', 'MRF.NS', 'GAIL.NS',
                        'ULTRACEMCO.NS', 'SHREECEM.NS', 'LT.NS', 'CONCOR.NS', 'RELIANCE.NS', 'IRCTC.NS',
                        'BALKRISIND.NS', 'IOC.NS', 'ADANIPORTS.NS', 'GRASIM.NS', 'POWERGRID.NS', 'INDIGO.NS',
                        'INDHOTEL.NS', 'APOLLOHOSP.NS', 'BPCL.NS', 'HINDPETRO.NS']
NIFTY_ALPHA_50 = ['DEEPAKFERT.NS', 'COALINDIA.NS', 'POLYCAB.NS', 'AMBUJACEM.NS', 'VBL.NS', 'YESBANK.NS', 'M&MFIN.NS',
                  'PFC.NS', 'CHOLAFIN.NS', 'FLUOROCHEM.NS', 'L&TFH.NS', 'UNIONBANK.NS', 'BANKINDIA.NS', 'PNB.NS',
                  'SCHAEFFLER.NS', 'M&M.NS', 'PHOENIXLTD.NS', 'IDFC.NS', 'IDFCFIRSTB.NS', 'CANBK.NS', 'APOLLOTYRE.NS',
                  'SIEMENS.NS', 'TVSMOTOR.NS', 'FEDERALBNK.NS', 'INDIANB.NS', 'ABB.NS', 'MRF.NS', 'TIINDIA.NS',
                  'NHPC.NS', 'BANKBARODA.NS', 'ABCAPITAL.NS', 'ZYDUSLIFE.NS', 'TIMKEN.NS', 'JINDALSTEL.NS', 'HAL.NS',
                  'POONAWALLA.NS', 'BHEL.NS', 'BRITANNIA.NS', 'BEL.NS', 'ADANIPOWER.NS', 'INDHOTEL.NS', 'ESCORTS.NS',
                  'ITC.NS', 'CGPOWER.NS', 'CUMMINSIND.NS', 'BAJAJHLDNG.NS', 'APLAPOLLO.NS', 'IIFL.NS', 'KARURVYSYA.NS',
                  'KPITTECH.NS']
NIFTY_SERVICES_SECTOR = ['DMART.NS', 'SHRIRAMFIN.NS', 'TATAPOWER.NS', 'BAJFINANCE.NS', 'BHARTIARTL.NS', 'NTPC.NS',
                         'BAJAJFINSV.NS', 'HCLTECH.NS', 'HDFCLIFE.NS', 'INDUSINDBK.NS', 'ICICIGI.NS', 'ICICIBANK.NS',
                         'WIPRO.NS', 'AXISBANK.NS', 'KOTAKBANK.NS', 'SBILIFE.NS', 'SBIN.NS', 'GAIL.NS', 'TECHM.NS',
                         'HDFC.NS', 'HDFCBANK.NS', 'TCS.NS', 'ADANIPORTS.NS', 'POWERGRID.NS', 'NAUKRI.NS', 'INFY.NS',
                         'APOLLOHOSP.NS', 'ATGL.NS', 'ADANIGREEN.NS', 'ADANITRANS.NS']
NIFTY_50 = ['HEROMOTOCO.NS', 'COALINDIA.NS', 'BAJAJ-AUTO.NS', 'MARUTI.NS', 'DIVISLAB.NS', 'ONGC.NS', 'EICHERMOT.NS',
            'BAJFINANCE.NS', 'UPL.NS', 'BHARTIARTL.NS', 'NTPC.NS', 'BAJAJFINSV.NS', 'HCLTECH.NS', 'HDFCLIFE.NS',
            'M&M.NS', 'TATACONSUM.NS', 'INDUSINDBK.NS', 'DRREDDY.NS', 'TITAN.NS', 'ICICIBANK.NS', 'TATAMOTORS.NS',
            'WIPRO.NS', 'AXISBANK.NS', 'KOTAKBANK.NS', 'ASIANPAINT.NS', 'SBILIFE.NS', 'SBIN.NS', 'TECHM.NS',
            'ULTRACEMCO.NS', 'LT.NS', 'HDFC.NS', 'HDFCBANK.NS', 'RELIANCE.NS', 'NESTLEIND.NS', 'TCS.NS', 'SUNPHARMA.NS',
            'TATASTEEL.NS', 'ADANIPORTS.NS', 'BRITANNIA.NS', 'GRASIM.NS', 'POWERGRID.NS', 'HINDALCO.NS', 'JSWSTEEL.NS',
            'HINDUNILVR.NS', 'CIPLA.NS', 'ITC.NS', 'INFY.NS', 'APOLLOHOSP.NS', 'ADANIENT.NS', 'BPCL.NS']
NIFTY_TOTAL_MARKET = ['DHANI.NS', 'MOL.NS', 'RVNL.NS', 'FAIRCHEMOR.NS', 'BCG.NS', 'JBMA.NS', 'GATI.NS', 'MANALIPETC.NS',
                      'JINDALPOLY.NS', 'FILATEX.NS', 'LXCHEM.NS', 'VAIBHAVGBL.NS', 'RTNPOWER.NS', 'BALAMINES.NS',
                      'HERITGFOOD.NS', 'HIL.NS', 'HCC.NS', 'TIPSINDLTD.NS', 'TANLA.NS', 'COSMOFIRST.NS',
                      'ASTRAMICRO.NS', 'POKARNA.NS', 'BECTORFOOD.NS', 'KAYNES.NS', 'CAMLINFINE.NS', 'CIGNITITEC.NS',
                      'DCXINDIA.NS', 'SIS.NS', 'UCOBANK.NS', 'HINDOILEXP.NS', 'GTLINFRA.NS', 'KRSNAA.NS', 'IOLCP.NS',
                      'GMRINFRA.NS', 'PNBHOUSING.NS', 'POLYPLEX.NS', 'HERANBA.NS', 'BOMDYEING.NS', 'MINDACORP.NS',
                      'GUJALKALI.NS', 'FORCEMOT.NS', 'HEMIPROP.NS', 'GRMOVER.NS', 'RTNINDIA.NS', 'PPLPHARMA.NS',
                      'ADVENZYMES.NS', 'SOUTHBANK.NS', 'MAHSEAMLES.NS', 'EMUDHRA.NS', 'IDEA.NS', 'RAJRATAN.NS',
                      'SARDAEN.NS', 'WELSPUNIND.NS', 'STAR.NS', 'ALOKINDS.NS', 'AVANTIFEED.NS', 'VSTTILLERS.NS',
                      'DCAL.NS', 'PGHH.NS', 'SOTL.NS', 'INDIGOPNTS.NS', 'CAMS.NS', 'TCNSBRANDS.NS', 'GRAPHITE.NS',
                      'IRFC.NS', 'PRICOLLTD.NS', 'RPOWER.NS', 'TEJASNET.NS', 'AGI.NS', 'CARTRADE.NS', 'KIRIINDUS.NS',
                      'HNDFDS.NS', 'FACT.NS', 'JWL.NS', 'CLEAN.NS', 'DMART.NS', 'OLECTRA.NS', 'TTML.NS', 'IEX.NS',
                      'PRSMJOHNSN.NS', 'VENKEYS.NS', 'MAHABANK.NS', 'ORIENTCEM.NS', 'THOMASCOOK.NS', 'JUBLPHARMA.NS',
                      'STLTECH.NS', 'EASEMYTRIP.NS', 'BAJAJHIND.NS', 'LUXIND.NS', 'KIRLOSBROS.NS', 'BANDHANBNK.NS',
                      'RELIGARE.NS', 'MANINFRA.NS', 'LATENTVIEW.NS', 'MAYURUNIQ.NS', 'JSWENERGY.NS', 'JPPOWER.NS',
                      'TIMETECHNO.NS', 'SCHNEIDER.NS', 'DALMIASUG.NS', 'TVTODAY.NS', 'BSE.NS', 'RUPA.NS', 'DOLLAR.NS',
                      'ELECTCAST.NS', 'WELENT.NS', 'BFUTILITIE.NS', 'NEULANDLAB.NS', 'STYRENIX.NS', 'HEG.NS',
                      'TIRUMALCHM.NS', 'LAURUSLABS.NS', 'UJJIVANSFB.NS', 'MSUMI.NS', 'BEPL.NS', 'IFCI.NS', 'KSB.NS',
                      'VAKRANGEE.NS', 'ISGEC.NS', 'PURVA.NS', 'SHYAMMETL.NS', 'SIYSIL.NS', 'DELTACORP.NS', 'SAFARI.NS',
                      'CHENNPETRO.NS', 'TV18BRDCST.NS', 'APARINDS.NS', 'MSTCLTD.NS', 'TIDEWATER.NS', 'WOCKPHARMA.NS',
                      'SUPRIYA.NS', 'NAVA.NS', 'DBREALTY.NS', 'VALIANTORG.NS', 'IRCON.NS', 'SURYAROSNI.NS',
                      'IBREALEST.NS', 'RAILTEL.NS', 'DATAPATTNS.NS', 'OIL.NS', 'EDELWEISS.NS', 'ARVIND.NS',
                      'DEEPAKFERT.NS', 'HAPPSTMNDS.NS', 'GNFC.NS', 'DWARKESH.NS', 'CENTURYTEX.NS', 'NETWORK18.NS',
                      'IPL.NS', 'IOB.NS', 'IDBI.NS', 'SUNTECK.NS', 'NAM-INDIA.NS', 'GREAVESCOT.NS', 'GRINFRA.NS',
                      'RENUKA.NS', 'AMIORG.NS', 'HEROMOTOCO.NS', 'GODREJAGRO.NS', 'GMDCLTD.NS', 'HUDCO.NS', 'HCG.NS',
                      'WABAG.NS', 'SOLARA.NS', 'CHEMPLASTS.NS', 'OPTIEMUS.NS', 'ACCELYA.NS', 'INTELLECT.NS', 'EMIL.NS',
                      'MHRIL.NS', 'CSBBANK.NS', 'ALKYLAMINE.NS', 'JUBLINGREA.NS', 'WELCORP.NS', 'VOLTAMP.NS',
                      'BALRAMCHIN.NS', 'CENTRALBK.NS', 'GREENPLY.NS', 'SUNDARMFIN.NS', 'SSWL.NS', 'MAHINDCIE.NS',
                      'MOTILALOFS.NS', 'GALAXYSURF.NS', 'TRIVENI.NS', 'KCP.NS', 'JMFINANCIL.NS', 'SUZLON.NS',
                      'ANANTRAJ.NS', 'NESCO.NS', 'VEDL.NS', 'COALINDIA.NS', 'DBL.NS', 'RCF.NS', 'HATHWAY.NS', 'VTL.NS',
                      'ICIL.NS', 'NYKAA.NS', 'CANFINHOME.NS', 'CHAMBLFERT.NS', 'SONATSOFTW.NS', 'SYRMA.NS',
                      'STOVEKRAFT.NS', 'WSTCSTPAPR.NS', 'CONFIPET.NS', 'MMTC.NS', 'GLENMARK.NS', 'ISEC.NS', 'ASHOKA.NS',
                      'SPICEJET.NS', 'DEN.NS', 'PRIVISCL.NS', 'NATCOPHARM.NS', 'SWSOLAR.NS', 'MOLDTKPAC.NS', 'NFL.NS',
                      'BORORENEW.NS', 'INGERRAND.NS', 'BAJAJ-AUTO.NS', 'POLYCAB.NS', 'AMBUJACEM.NS', 'MRPL.NS',
                      'RBA.NS', 'JTEKTINDIA.NS', 'RAIN.NS', 'HLEGLAS.NS', 'GPIL.NS', 'MARUTI.NS', 'CDSL.NS', 'GLS.NS',
                      'MOREPENLAB.NS', 'VARROC.NS', 'GATEWAY.NS', 'GUFICBIO.NS', 'BBTC.NS', 'CROMPTON.NS', 'GRAVITA.NS',
                      'VBL.NS', 'BSOFT.NS', 'PCJEWELLER.NS', 'ACC.NS', 'MOIL.NS', 'PARAS.NS', 'HBLPOWER.NS',
                      'GODREJIND.NS', 'EIDPARRY.NS', 'DATAMATICS.NS', 'LGBBROSLTD.NS', 'CAPLIPOINT.NS', 'GABRIEL.NS',
                      'APCOTEXIND.NS', 'YESBANK.NS', 'M&MFIN.NS', 'PFC.NS', 'PRINCEPIPE.NS', 'PTC.NS', 'CHOLAFIN.NS',
                      'JAICORPLTD.NS', 'SHRIRAMFIN.NS', 'DCMSHRIRAM.NS', 'CESC.NS', 'PETRONET.NS', 'BIRLACORPN.NS',
                      'UFLEX.NS', 'PGEL.NS', 'RBLBANK.NS', 'DAAWAT.NS', 'ELECON.NS', 'GRANULES.NS', 'J&KBANK.NS',
                      'NRBBEARING.NS', 'AIAENG.NS', 'MAITHANALL.NS', 'STARHEALTH.NS', 'ANDHRSUGAR.NS', 'GLOBUSSPR.NS',
                      'PFIZER.NS', 'AAVAS.NS', 'GSFC.NS', 'IBULHSGFIN.NS', 'FLUOROCHEM.NS', 'TARSONS.NS', 'MAHLOG.NS',
                      'DIVISLAB.NS', 'TATAPOWER.NS', 'JINDALSAW.NS', 'LICI.NS', 'GICRE.NS', 'TCIEXP.NS', 'KFINTECH.NS',
                      'NIACL.NS', 'L&TFH.NS', 'CCL.NS', 'LTTS.NS', 'UNIONBANK.NS', 'FDC.NS', 'CUB.NS', 'FIEMIND.NS',
                      'RALLIS.NS', 'TTKPRESTIG.NS', 'CMSINFO.NS', 'BANKINDIA.NS', 'SHARDACROP.NS', 'SHILPAMED.NS',
                      'ONGC.NS', 'MAPMYINDIA.NS', 'HSCL.NS', 'INOXWIND.NS', 'ZOMATO.NS', 'PDSL.NS', 'TATAMTRDVR.NS',
                      'TATAINVEST.NS', 'HINDZINC.NS', 'EICHERMOT.NS', 'MIDHANI.NS', 'BAJFINANCE.NS', 'ROLEXRINGS.NS',
                      'FIVESTAR.NS', 'VSTIND.NS', 'THERMAX.NS', 'EQUITASBNK.NS', 'SUNDRMFAST.NS', 'ARVINDFASN.NS',
                      'PRESTIGE.NS', 'HIKAL.NS', 'BALMLAWRIE.NS', 'UPL.NS', 'JAMNAAUTO.NS', 'ASAHIINDIA.NS',
                      'JINDWORLD.NS', 'MFL.NS', 'BHARTIARTL.NS', 'PNB.NS', 'JISLJALEQS.NS', 'NTPC.NS', 'LICHSGFIN.NS',
                      'ECLERX.NS', 'AJANTPHARM.NS', 'SONACOMS.NS', 'GODREJPROP.NS', 'AMARAJABAT.NS', 'RATEGAIN.NS',
                      'DISHTV.NS', 'COCHINSHIP.NS', 'ACE.NS', 'NUVOCO.NS', 'SCHAEFFLER.NS', 'MTARTECH.NS', 'SULA.NS',
                      'INDOCO.NS', 'REDINGTON.NS', 'HINDCOPPER.NS', 'ENGINERSIN.NS', 'KKCL.NS', 'USHAMART.NS',
                      'CASTROLIND.NS', 'UTIAMC.NS', 'ITI.NS', 'RECLTD.NS', 'SEQUENT.NS', 'ASTERDM.NS', 'ETHOSLTD.NS',
                      'DIXON.NS', 'BAJAJCON.NS', 'FINOPB.NS', 'NATIONALUM.NS', 'AMBER.NS', 'PATANJALI.NS', 'SAIL.NS',
                      'DEVYANI.NS', 'MAHLIFE.NS', 'BAJAJFINSV.NS', 'VGUARD.NS', 'HDFCAMC.NS', 'ASHOKLEY.NS',
                      'BIOCON.NS', 'JKLAKSHMI.NS', 'GREENPANEL.NS', 'WESTLIFE.NS', 'TATVA.NS', 'ERIS.NS', 'HCLTECH.NS',
                      'DLF.NS', 'FORTIS.NS', 'TATAELXSI.NS', 'EXIDEIND.NS', 'RELINFRA.NS', 'QUESS.NS', 'GLAND.NS',
                      'HDFCLIFE.NS', 'PGHL.NS', 'HFCL.NS', 'M&M.NS', 'TATACONSUM.NS', 'GAEL.NS', 'MARKSANS.NS',
                      'SBICARD.NS', 'AARTIDRUGS.NS', 'INDUSINDBK.NS', 'THYROCARE.NS', 'VIJAYA.NS', 'UJJIVAN.NS',
                      'FCL.NS', 'IMFA.NS', 'INFIBEAM.NS', 'KRBL.NS', 'PHOENIXLTD.NS', 'SKFINDIA.NS', 'SANOFI.NS',
                      'NCC.NS', 'IDFC.NS', 'IFBIND.NS', 'POWERMECH.NS', 'MANAPPURAM.NS', 'RITES.NS', 'IDFCFIRSTB.NS',
                      'FINEORG.NS', 'TATASTLLP.NS', 'COLPAL.NS', 'CANBK.NS', 'ICICIGI.NS', 'PEL.NS', 'HGINFRA.NS',
                      'CARBORUNIV.NS', 'INDIACEM.NS', 'NOCIL.NS', 'MOTHERSON.NS', 'SOBHA.NS', 'PARADEEP.NS',
                      'APOLLOTYRE.NS', 'HARSHA.NS', 'SUBEXLTD.NS', 'DRREDDY.NS', 'JKPAPER.NS', 'TITAN.NS',
                      'ICICIBANK.NS', 'FINPIPE.NS', 'TATAMOTORS.NS', 'GPPL.NS', 'WIPRO.NS', 'SUNTV.NS', 'AXISBANK.NS',
                      'RAINBOW.NS', 'PRUDENT.NS', 'ZENSARTECH.NS', 'LALPATHLAB.NS', 'PSPPROJECT.NS', 'WHIRLPOOL.NS',
                      'VINATIORGA.NS', 'SIEMENS.NS', 'BEML.NS', 'JPASSOCIAT.NS', 'BUTTERFLY.NS', 'ZEEL.NS', 'NBCC.NS',
                      'DCBBANK.NS', 'SHAREINDIA.NS', 'KOTAKBANK.NS', 'SUPRAJIT.NS', 'BRIGADE.NS', 'EMAMILTD.NS',
                      'NAVNETEDUL.NS', 'BATAINDIA.NS', 'COFORGE.NS', 'NAZARA.NS', 'TVSMOTOR.NS', 'ABFRL.NS',
                      'ICICIPRULI.NS', 'VOLTAS.NS', 'KIRLFER.NS', 'KSCL.NS', 'ZYDUSWELL.NS', 'ROSSARI.NS',
                      'EVEREADY.NS', 'ABBOTINDIA.NS', 'ASIANPAINT.NS', 'AFFLE.NS', 'UBL.NS', 'CARYSIL.NS', 'VMART.NS',
                      'KENNAMET.NS', 'HEIDELBERG.NS', 'SHANTIGEAR.NS', 'KANSAINER.NS', 'METROPOLIS.NS', 'CREDITACC.NS',
                      'TRIDENT.NS', 'SOMANYCERA.NS', 'FEDERALBNK.NS', 'NEOGEN.NS', 'KNRCON.NS', 'TORNTPHARM.NS',
                      'TORNTPOWER.NS', 'INDIANB.NS', 'ABB.NS', 'INDUSTOWER.NS', 'TATACHEM.NS', 'PANAMAPET.NS',
                      'BLUESTARCO.NS', 'MRF.NS', 'FINCABLES.NS', 'RAMCOCEM.NS', 'VIPIND.NS', 'RATNAMANI.NS',
                      'LINDEINDIA.NS', 'COROMANDEL.NS', 'AARTIIND.NS', 'ANGELONE.NS', 'SBILIFE.NS', 'SBIN.NS',
                      'OFSS.NS', 'CARERATING.NS', 'GAIL.NS', 'GUJGASLTD.NS', 'MFSL.NS', 'BAYERCROP.NS', 'CYIENT.NS',
                      'TECHM.NS', 'TATAMETALI.NS', 'ULTRACEMCO.NS', 'GMMPFAUDLR.NS', 'MPHASIS.NS', 'PAYTM.NS',
                      'CERA.NS', 'LEMONTREE.NS', 'PCBL.NS', 'TIINDIA.NS', 'NHPC.NS', 'GESHIP.NS', 'SHREECEM.NS',
                      'BANKBARODA.NS', 'ABCAPITAL.NS', 'LT.NS', 'SPANDANA.NS', 'ASTRAL.NS', 'NLCINDIA.NS',
                      'KALYANKJIL.NS', 'HONAUT.NS', 'AUROPHARMA.NS', 'HDFC.NS', 'BOSCHLTD.NS', 'MAZDOCK.NS',
                      'SAGCEM.NS', 'CONCOR.NS', 'HAVELLS.NS', 'RELAXO.NS', 'SHOPERSTOP.NS', 'DALBHARAT.NS', 'LUPIN.NS',
                      'MUTHOOTFIN.NS', 'ZYDUSLIFE.NS', 'LAXMIMACH.NS', 'KPRMILL.NS', 'KAJARIACER.NS', 'TIMKEN.NS',
                      'JKIL.NS', 'DABUR.NS', 'CEATLTD.NS', 'HDFCBANK.NS', 'KEI.NS', 'JINDALSTEL.NS', 'PRAJIND.NS',
                      'OBEROIRLTY.NS', 'NMDC.NS', 'RELIANCE.NS', 'GOKEX.NS', 'SUPREMEIND.NS', 'IPCALAB.NS',
                      'NESTLEIND.NS', 'BHARATFORG.NS', 'SUMICHEM.NS', 'MARICO.NS', 'TINPLATE.NS', 'METROBRAND.NS',
                      'SPARC.NS', 'ANANDRATHI.NS', 'INDIAMART.NS', 'KOLTEPATIL.NS', 'TATACOMM.NS', 'IRCTC.NS', 'BLS.NS',
                      'JKTYRE.NS', 'HAL.NS', 'TCS.NS', 'BDL.NS', 'CHALET.NS', 'BAJAJELEC.NS', 'SWANENERGY.NS',
                      'RAJESHEXPO.NS', 'BALKRISIND.NS', 'AEGISCHEM.NS', 'POONAWALLA.NS', 'CENTURYPLY.NS', 'HGS.NS',
                      'GARFIBRES.NS', 'CRISIL.NS', 'LTIM.NS', 'LANDMARK.NS', 'BHEL.NS', 'JYOTHYLAB.NS', 'KIRLOSENG.NS',
                      'IOC.NS', 'GOODYEAR.NS', 'PAGEIND.NS', 'GODREJCP.NS', 'SUNPHARMA.NS', 'TATASTEEL.NS',
                      'SUVENPHAR.NS', 'ICRA.NS', 'ALKEM.NS', 'ADANIPORTS.NS', 'MANYAVAR.NS', 'SUDARSCHEM.NS', 'SBCL.NS',
                      'BRITANNIA.NS', 'GRASIM.NS', 'FUSION.NS', 'TEGA.NS', 'MCX.NS', 'CHOLAHLDNG.NS', 'RHIM.NS',
                      'POWERGRID.NS', 'MCDOWELL-N.NS', 'ASTRAZEN.NS', 'INDIGO.NS', 'JKCEMENT.NS', 'ATUL.NS', 'BEL.NS',
                      'BERGEPAINT.NS', 'BASF.NS', 'STARCEMENT.NS', 'JSL.NS', 'IRB.NS', 'SANSERA.NS', 'CAMPUS.NS',
                      'MASTEK.NS', 'TMB.NS', 'VESUVIUS.NS', 'EIHOTEL.NS', 'FSL.NS', 'APLLTD.NS', 'ELGIEQUIP.NS',
                      'MMFL.NS', 'SJVN.NS', 'HINDALCO.NS', 'ENDURANCE.NS', 'ADANIPOWER.NS', 'UNIPARTS.NS',
                      'INDHOTEL.NS', 'TECHNOE.NS', 'JSWSTEEL.NS', 'GSPL.NS', 'UNICHEMLAB.NS', 'JUBLFOOD.NS',
                      'INDIAGLYCO.NS', 'PNCINFRA.NS', 'ESABINDIA.NS', 'GRINDWELL.NS', 'HINDUNILVR.NS', 'IONEXCHANG.NS',
                      'SYMPHONY.NS', 'BLUEDART.NS', 'ROUTE.NS', 'NAUKRI.NS', 'KIMS.NS', 'CIPLA.NS', 'SAPPHIRE.NS',
                      'AKZOINDIA.NS', 'ESCORTS.NS', 'DELHIVERY.NS', 'ITC.NS', 'CGPOWER.NS', 'NAVINFLUOR.NS',
                      '3MINDIA.NS', 'NH.NS', 'APTUS.NS', 'MAHSCOOTER.NS', 'RADICO.NS', 'POLYMED.NS', 'PIDILITIND.NS',
                      'PVR.NS', 'RKFORGE.NS', 'INFY.NS', 'NEWGEN.NS', 'BIKAJI.NS', 'KEC.NS', 'AETHER.NS', 'SYNGENE.NS',
                      'GRSE.NS', 'PAISALO.NS', 'JBCHEPHARM.NS', 'EPL.NS', 'VRLLOG.NS', 'CUMMINSIND.NS', 'AUTOAXLES.NS',
                      'HINDWAREAP.NS', 'BESTAGRO.NS', 'TCI.NS', 'POWERINDIA.NS', 'LAOPALA.NS', 'SOLARINDS.NS',
                      'TRENT.NS', 'APOLLOPIPE.NS', 'BAJAJHLDNG.NS', 'TEAMLEASE.NS', 'PERSISTENT.NS', 'JUSTDIAL.NS',
                      'GOCOLORS.NS', 'SPLPETRO.NS', 'IGL.NS', 'ACI.NS', 'LODHA.NS', 'ZFCVINDIA.NS', 'PIIND.NS',
                      'APOLLOHOSP.NS', 'DEEPAKNTR.NS', 'TRITURBINE.NS', 'ADANIENT.NS', 'RAYMOND.NS', '360ONE.NS',
                      'SRF.NS', 'MEDPLUS.NS', 'MAXHEALTH.NS', 'APLAPOLLO.NS', 'ATGL.NS', 'POLICYBZR.NS', 'AUBANK.NS',
                      'AWL.NS', 'ANURAS.NS', 'GLAXO.NS', 'RUSTOMJEE.NS', 'MASFIN.NS', 'UNOMINDA.NS', 'ASTEC.NS',
                      'IIFL.NS', 'NDTV.NS', 'GODFRYPHLP.NS', 'KALPATPOWR.NS', 'HOMEFIRST.NS', 'BARBEQUE.NS',
                      'CRAFTSMAN.NS', 'BPCL.NS', 'KARURVYSYA.NS', 'KTKBANK.NS', 'HINDPETRO.NS', 'MEDANTA.NS',
                      'ADANIGREEN.NS', 'ADANITRANS.NS', 'ORIENTELEC.NS', 'MGL.NS', 'CGCL.NS', 'KPITTECH.NS']
NIFTY_NEXT_50 = ['PGHH.NS', 'DMART.NS', 'VEDL.NS', 'NYKAA.NS', 'AMBUJACEM.NS', 'VBL.NS', 'ACC.NS', 'CHOLAFIN.NS',
                 'TATAPOWER.NS', 'LICI.NS', 'ZOMATO.NS', 'HDFCAMC.NS', 'DLF.NS', 'SBICARD.NS', 'COLPAL.NS', 'CANBK.NS',
                 'ICICIGI.NS', 'MOTHERSON.NS', 'SIEMENS.NS', 'ICICIPRULI.NS', 'TORNTPHARM.NS', 'ABB.NS',
                 'INDUSTOWER.NS', 'GAIL.NS', 'SHREECEM.NS', 'BANKBARODA.NS', 'BOSCHLTD.NS', 'HAVELLS.NS',
                 'MUTHOOTFIN.NS', 'DABUR.NS', 'MARICO.NS', 'IRCTC.NS', 'HAL.NS', 'LTIM.NS', 'IOC.NS', 'PAGEIND.NS',
                 'GODREJCP.NS', 'MCDOWELL-N.NS', 'INDIGO.NS', 'BEL.NS', 'BERGEPAINT.NS', 'NAUKRI.NS', 'PIDILITIND.NS',
                 'BAJAJHLDNG.NS', 'PIIND.NS', 'SRF.NS', 'ATGL.NS', 'AWL.NS', 'ADANIGREEN.NS', 'ADANITRANS.NS']
NIFTY_IT = ['LTTS.NS', 'HCLTECH.NS', 'WIPRO.NS', 'COFORGE.NS', 'TECHM.NS', 'MPHASIS.NS', 'TCS.NS', 'LTIM.NS', 'INFY.NS',
            'PERSISTENT.NS']
NIFTY500_MULTICAP_50_25_25 = ['RVNL.NS', 'BCG.NS', 'JBMA.NS', 'LXCHEM.NS', 'VAIBHAVGBL.NS', 'BALAMINES.NS', 'TANLA.NS',
                              'UCOBANK.NS', 'GMRINFRA.NS', 'PNBHOUSING.NS', 'POLYPLEX.NS', 'GUJALKALI.NS',
                              'RTNINDIA.NS', 'PPLPHARMA.NS', 'IDEA.NS', 'WELSPUNIND.NS', 'AVANTIFEED.NS', 'PGHH.NS',
                              'INDIGOPNTS.NS', 'CAMS.NS', 'TCNSBRANDS.NS', 'GRAPHITE.NS', 'IRFC.NS', 'TEJASNET.NS',
                              'FACT.NS', 'CLEAN.NS', 'DMART.NS', 'OLECTRA.NS', 'TTML.NS', 'IEX.NS', 'PRSMJOHNSN.NS',
                              'MAHABANK.NS', 'JUBLPHARMA.NS', 'STLTECH.NS', 'EASEMYTRIP.NS', 'LUXIND.NS',
                              'BANDHANBNK.NS', 'LATENTVIEW.NS', 'JSWENERGY.NS', 'BSE.NS', 'HEG.NS', 'LAURUSLABS.NS',
                              'MSUMI.NS', 'KSB.NS', 'SHYAMMETL.NS', 'DELTACORP.NS', 'TV18BRDCST.NS', 'APARINDS.NS',
                              'IBREALEST.NS', 'DATAPATTNS.NS', 'OIL.NS', 'EDELWEISS.NS', 'DEEPAKFERT.NS',
                              'HAPPSTMNDS.NS', 'GNFC.NS', 'CENTURYTEX.NS', 'NETWORK18.NS', 'IOB.NS', 'IDBI.NS',
                              'SUNTECK.NS', 'NAM-INDIA.NS', 'GRINFRA.NS', 'RENUKA.NS', 'HEROMOTOCO.NS', 'GODREJAGRO.NS',
                              'HUDCO.NS', 'CHEMPLASTS.NS', 'INTELLECT.NS', 'MHRIL.NS', 'CSBBANK.NS', 'ALKYLAMINE.NS',
                              'JUBLINGREA.NS', 'WELCORP.NS', 'BALRAMCHIN.NS', 'CENTRALBK.NS', 'SUNDARMFIN.NS',
                              'MAHINDCIE.NS', 'MOTILALOFS.NS', 'GALAXYSURF.NS', 'TRIVENI.NS', 'JMFINANCIL.NS',
                              'SUZLON.NS', 'VEDL.NS', 'COALINDIA.NS', 'RCF.NS', 'VTL.NS', 'NYKAA.NS', 'CANFINHOME.NS',
                              'CHAMBLFERT.NS', 'SONATSOFTW.NS', 'MMTC.NS', 'GLENMARK.NS', 'ISEC.NS', 'NATCOPHARM.NS',
                              'SWSOLAR.NS', 'BORORENEW.NS', 'INGERRAND.NS', 'BAJAJ-AUTO.NS', 'POLYCAB.NS',
                              'AMBUJACEM.NS', 'MRPL.NS', 'RBA.NS', 'RAIN.NS', 'HLEGLAS.NS', 'MARUTI.NS', 'CDSL.NS',
                              'VARROC.NS', 'BBTC.NS', 'CROMPTON.NS', 'VBL.NS', 'BSOFT.NS', 'ACC.NS', 'GODREJIND.NS',
                              'EIDPARRY.NS', 'YESBANK.NS', 'M&MFIN.NS', 'PFC.NS', 'PRINCEPIPE.NS', 'CHOLAFIN.NS',
                              'SHRIRAMFIN.NS', 'DCMSHRIRAM.NS', 'CESC.NS', 'PETRONET.NS', 'BIRLACORPN.NS', 'UFLEX.NS',
                              'RBLBANK.NS', 'GRANULES.NS', 'AIAENG.NS', 'STARHEALTH.NS', 'PFIZER.NS', 'AAVAS.NS',
                              'GSFC.NS', 'IBULHSGFIN.NS', 'FLUOROCHEM.NS', 'MAHLOG.NS', 'DIVISLAB.NS', 'TATAPOWER.NS',
                              'LICI.NS', 'GICRE.NS', 'TCIEXP.NS', 'KFINTECH.NS', 'NIACL.NS', 'L&TFH.NS', 'CCL.NS',
                              'LTTS.NS', 'UNIONBANK.NS', 'FDC.NS', 'CUB.NS', 'RALLIS.NS', 'TTKPRESTIG.NS',
                              'BANKINDIA.NS', 'SHARDACROP.NS', 'ONGC.NS', 'MAPMYINDIA.NS', 'ZOMATO.NS', 'TATAMTRDVR.NS',
                              'TATAINVEST.NS', 'HINDZINC.NS', 'EICHERMOT.NS', 'BAJFINANCE.NS', 'FIVESTAR.NS',
                              'THERMAX.NS', 'EQUITASBNK.NS', 'SUNDRMFAST.NS', 'PRESTIGE.NS', 'HIKAL.NS', 'UPL.NS',
                              'JAMNAAUTO.NS', 'ASAHIINDIA.NS', 'JINDWORLD.NS', 'MFL.NS', 'BHARTIARTL.NS', 'PNB.NS',
                              'NTPC.NS', 'LICHSGFIN.NS', 'ECLERX.NS', 'AJANTPHARM.NS', 'SONACOMS.NS', 'GODREJPROP.NS',
                              'AMARAJABAT.NS', 'COCHINSHIP.NS', 'NUVOCO.NS', 'SCHAEFFLER.NS', 'MTARTECH.NS',
                              'REDINGTON.NS', 'HINDCOPPER.NS', 'ENGINERSIN.NS', 'CASTROLIND.NS', 'UTIAMC.NS', 'ITI.NS',
                              'RECLTD.NS', 'ASTERDM.NS', 'DIXON.NS', 'NATIONALUM.NS', 'AMBER.NS', 'PATANJALI.NS',
                              'SAIL.NS', 'DEVYANI.NS', 'MAHLIFE.NS', 'BAJAJFINSV.NS', 'VGUARD.NS', 'HDFCAMC.NS',
                              'ASHOKLEY.NS', 'BIOCON.NS', 'JKLAKSHMI.NS', 'GREENPANEL.NS', 'WESTLIFE.NS', 'HCLTECH.NS',
                              'DLF.NS', 'FORTIS.NS', 'TATAELXSI.NS', 'EXIDEIND.NS', 'QUESS.NS', 'GLAND.NS',
                              'HDFCLIFE.NS', 'HFCL.NS', 'M&M.NS', 'TATACONSUM.NS', 'GAEL.NS', 'SBICARD.NS',
                              'AARTIDRUGS.NS', 'INDUSINDBK.NS', 'VIJAYA.NS', 'INFIBEAM.NS', 'KRBL.NS', 'PHOENIXLTD.NS',
                              'SKFINDIA.NS', 'SANOFI.NS', 'NCC.NS', 'IDFC.NS', 'IFBIND.NS', 'MANAPPURAM.NS', 'RITES.NS',
                              'IDFCFIRSTB.NS', 'FINEORG.NS', 'COLPAL.NS', 'CANBK.NS', 'ICICIGI.NS', 'PEL.NS',
                              'CARBORUNIV.NS', 'INDIACEM.NS', 'NOCIL.NS', 'MOTHERSON.NS', 'SOBHA.NS', 'APOLLOTYRE.NS',
                              'DRREDDY.NS', 'JKPAPER.NS', 'TITAN.NS', 'ICICIBANK.NS', 'FINPIPE.NS', 'TATAMOTORS.NS',
                              'GPPL.NS', 'WIPRO.NS', 'SUNTV.NS', 'AXISBANK.NS', 'RAINBOW.NS', 'ZENSARTECH.NS',
                              'LALPATHLAB.NS', 'WHIRLPOOL.NS', 'VINATIORGA.NS', 'SIEMENS.NS', 'BEML.NS', 'ZEEL.NS',
                              'NBCC.NS', 'KOTAKBANK.NS', 'SUPRAJIT.NS', 'BRIGADE.NS', 'EMAMILTD.NS', 'BATAINDIA.NS',
                              'COFORGE.NS', 'NAZARA.NS', 'TVSMOTOR.NS', 'ABFRL.NS', 'ICICIPRULI.NS', 'VOLTAS.NS',
                              'ZYDUSWELL.NS', 'ROSSARI.NS', 'ABBOTINDIA.NS', 'ASIANPAINT.NS', 'AFFLE.NS', 'UBL.NS',
                              'VMART.NS', 'KENNAMET.NS', 'KANSAINER.NS', 'METROPOLIS.NS', 'CREDITACC.NS', 'TRIDENT.NS',
                              'FEDERALBNK.NS', 'KNRCON.NS', 'TORNTPHARM.NS', 'TORNTPOWER.NS', 'INDIANB.NS', 'ABB.NS',
                              'INDUSTOWER.NS', 'TATACHEM.NS', 'BLUESTARCO.NS', 'MRF.NS', 'FINCABLES.NS', 'RAMCOCEM.NS',
                              'VIPIND.NS', 'RATNAMANI.NS', 'LINDEINDIA.NS', 'COROMANDEL.NS', 'AARTIIND.NS',
                              'ANGELONE.NS', 'SBILIFE.NS', 'SBIN.NS', 'OFSS.NS', 'GAIL.NS', 'GUJGASLTD.NS', 'MFSL.NS',
                              'BAYERCROP.NS', 'CYIENT.NS', 'TECHM.NS', 'ULTRACEMCO.NS', 'GMMPFAUDLR.NS', 'MPHASIS.NS',
                              'PAYTM.NS', 'CERA.NS', 'LEMONTREE.NS', 'PCBL.NS', 'TIINDIA.NS', 'NHPC.NS', 'GESHIP.NS',
                              'SHREECEM.NS', 'BANKBARODA.NS', 'ABCAPITAL.NS', 'LT.NS', 'ASTRAL.NS', 'NLCINDIA.NS',
                              'KALYANKJIL.NS', 'HONAUT.NS', 'AUROPHARMA.NS', 'HDFC.NS', 'BOSCHLTD.NS', 'MAZDOCK.NS',
                              'CONCOR.NS', 'HAVELLS.NS', 'RELAXO.NS', 'SHOPERSTOP.NS', 'DALBHARAT.NS', 'LUPIN.NS',
                              'MUTHOOTFIN.NS', 'ZYDUSLIFE.NS', 'LAXMIMACH.NS', 'KPRMILL.NS', 'KAJARIACER.NS',
                              'TIMKEN.NS', 'DABUR.NS', 'CEATLTD.NS', 'HDFCBANK.NS', 'KEI.NS', 'JINDALSTEL.NS',
                              'PRAJIND.NS', 'OBEROIRLTY.NS', 'RELIANCE.NS', 'NMDC.NS', 'SUPREMEIND.NS', 'IPCALAB.NS',
                              'NESTLEIND.NS', 'BHARATFORG.NS', 'SUMICHEM.NS', 'MARICO.NS', 'METROBRAND.NS', 'SPARC.NS',
                              'INDIAMART.NS', 'TATACOMM.NS', 'IRCTC.NS', 'BLS.NS', 'HAL.NS', 'TCS.NS', 'BDL.NS',
                              'CHALET.NS', 'BAJAJELEC.NS', 'SWANENERGY.NS', 'RAJESHEXPO.NS', 'BALKRISIND.NS',
                              'AEGISCHEM.NS', 'POONAWALLA.NS', 'CENTURYPLY.NS', 'HGS.NS', 'GARFIBRES.NS', 'CRISIL.NS',
                              'LTIM.NS', 'BHEL.NS', 'JYOTHYLAB.NS', 'IOC.NS', 'PAGEIND.NS', 'GODREJCP.NS',
                              'SUNPHARMA.NS', 'TATASTEEL.NS', 'SUVENPHAR.NS', 'ALKEM.NS', 'ADANIPORTS.NS',
                              'MANYAVAR.NS', 'BRITANNIA.NS', 'GRASIM.NS', 'MCX.NS', 'CHOLAHLDNG.NS', 'RHIM.NS',
                              'POWERGRID.NS', 'MCDOWELL-N.NS', 'INDIGO.NS', 'JKCEMENT.NS', 'ATUL.NS', 'BEL.NS',
                              'BERGEPAINT.NS', 'BASF.NS', 'JSL.NS', 'IRB.NS', 'CAMPUS.NS', 'MASTEK.NS', 'TMB.NS',
                              'EIHOTEL.NS', 'FSL.NS', 'APLLTD.NS', 'ELGIEQUIP.NS', 'SJVN.NS', 'HINDALCO.NS',
                              'ENDURANCE.NS', 'ADANIPOWER.NS', 'INDHOTEL.NS', 'JSWSTEEL.NS', 'GSPL.NS', 'JUBLFOOD.NS',
                              'PNCINFRA.NS', 'GRINDWELL.NS', 'HINDUNILVR.NS', 'BLUEDART.NS', 'ROUTE.NS', 'NAUKRI.NS',
                              'KIMS.NS', 'CIPLA.NS', 'SAPPHIRE.NS', 'ESCORTS.NS', 'DELHIVERY.NS', 'ITC.NS',
                              'CGPOWER.NS', 'NAVINFLUOR.NS', '3MINDIA.NS', 'NH.NS', 'APTUS.NS', 'RADICO.NS',
                              'POLYMED.NS', 'PIDILITIND.NS', 'PVR.NS', 'INFY.NS', 'BIKAJI.NS', 'KEC.NS', 'AETHER.NS',
                              'SYNGENE.NS', 'JBCHEPHARM.NS', 'EPL.NS', 'CUMMINSIND.NS', 'TCI.NS', 'POWERINDIA.NS',
                              'SOLARINDS.NS', 'TRENT.NS', 'BAJAJHLDNG.NS', 'TEAMLEASE.NS', 'PERSISTENT.NS',
                              'JUSTDIAL.NS', 'GOCOLORS.NS', 'IGL.NS', 'ACI.NS', 'LODHA.NS', 'ZFCVINDIA.NS', 'PIIND.NS',
                              'APOLLOHOSP.NS', 'DEEPAKNTR.NS', 'TRITURBINE.NS', 'ADANIENT.NS', 'RAYMOND.NS',
                              '360ONE.NS', 'SRF.NS', 'MEDPLUS.NS', 'MAXHEALTH.NS', 'APLAPOLLO.NS', 'ATGL.NS',
                              'POLICYBZR.NS', 'AUBANK.NS', 'AWL.NS', 'ANURAS.NS', 'GLAXO.NS', 'RUSTOMJEE.NS',
                              'UNOMINDA.NS', 'IIFL.NS', 'GODFRYPHLP.NS', 'KALPATPOWR.NS', 'HOMEFIRST.NS',
                              'CRAFTSMAN.NS', 'BPCL.NS', 'KARURVYSYA.NS', 'HINDPETRO.NS', 'MEDANTA.NS', 'ADANIGREEN.NS',
                              'ADANITRANS.NS', 'ORIENTELEC.NS', 'MGL.NS', 'CGCL.NS', 'KPITTECH.NS']
NIFTY_MEDIA = ['TV18BRDCST.NS', 'NETWORK18.NS', 'HATHWAY.NS', 'DISHTV.NS', 'SUNTV.NS', 'ZEEL.NS', 'NAVNETEDUL.NS',
               'NAZARA.NS', 'PVR.NS', 'NDTV.NS']
NIFTY200_QUALITY_30 = ['IEX.NS', 'HEROMOTOCO.NS', 'COALINDIA.NS', 'BAJAJ-AUTO.NS', 'DIVISLAB.NS', 'LTTS.NS',
                       'HCLTECH.NS', 'COLPAL.NS', 'SUNTV.NS', 'LALPATHLAB.NS', 'ABBOTINDIA.NS', 'ASIANPAINT.NS',
                       'COROMANDEL.NS', 'OFSS.NS', 'TECHM.NS', 'HAVELLS.NS', 'MUTHOOTFIN.NS', 'DABUR.NS',
                       'NESTLEIND.NS', 'MARICO.NS', 'TCS.NS', 'LTIM.NS', 'PAGEIND.NS', 'BRITANNIA.NS', 'BERGEPAINT.NS',
                       'HINDUNILVR.NS', 'ITC.NS', 'PIDILITIND.NS', 'INFY.NS', 'IGL.NS']
NIFTY_PRIVATE_BANK = ['BANDHANBNK.NS', 'RBLBANK.NS', 'CUB.NS', 'INDUSINDBK.NS', 'IDFCFIRSTB.NS', 'ICICIBANK.NS',
                      'AXISBANK.NS', 'KOTAKBANK.NS', 'FEDERALBNK.NS', 'HDFCBANK.NS']
NIFTY_FINANCIAL_SERVICES_25_50 = ['IEX.NS', 'PFC.NS', 'CHOLAFIN.NS', 'SHRIRAMFIN.NS', 'BAJFINANCE.NS', 'RECLTD.NS',
                                  'BAJAJFINSV.NS', 'HDFCAMC.NS', 'HDFCLIFE.NS', 'SBICARD.NS', 'ICICIGI.NS',
                                  'ICICIBANK.NS', 'AXISBANK.NS', 'KOTAKBANK.NS', 'ICICIPRULI.NS', 'SBILIFE.NS',
                                  'SBIN.NS', 'HDFC.NS', 'MUTHOOTFIN.NS', 'HDFCBANK.NS']
NIFTY_HEALTHCARE_INDEX = ['LAURUSLABS.NS', 'GLENMARK.NS', 'GRANULES.NS', 'DIVISLAB.NS', 'BIOCON.NS', 'DRREDDY.NS',
                          'LALPATHLAB.NS', 'ABBOTINDIA.NS', 'METROPOLIS.NS', 'TORNTPHARM.NS', 'AUROPHARMA.NS',
                          'LUPIN.NS', 'ZYDUSLIFE.NS', 'IPCALAB.NS', 'SUNPHARMA.NS', 'ALKEM.NS', 'CIPLA.NS',
                          'SYNGENE.NS', 'APOLLOHOSP.NS', 'MAXHEALTH.NS']
NIFTY_MIDCAP_100 = ['NIFTY MIDCAP 100.NS', 'IDEA.NS', 'IRFC.NS', 'TTML.NS', 'BANDHANBNK.NS', 'JSWENERGY.NS',
                    'LAURUSLABS.NS', 'MSUMI.NS', 'OIL.NS', 'POLYCAB.NS', 'CROMPTON.NS', 'YESBANK.NS', 'M&MFIN.NS',
                    'PFC.NS', 'SHRIRAMFIN.NS', 'PETRONET.NS', 'FLUOROCHEM.NS', 'L&TFH.NS', 'LTTS.NS', 'UNIONBANK.NS',
                    'BANKINDIA.NS', 'HINDZINC.NS', 'PRESTIGE.NS', 'PNB.NS', 'LICHSGFIN.NS', 'SONACOMS.NS',
                    'GODREJPROP.NS', 'RECLTD.NS', 'DIXON.NS', 'PATANJALI.NS', 'SAIL.NS', 'DEVYANI.NS', 'ASHOKLEY.NS',
                    'BIOCON.NS', 'FORTIS.NS', 'TATAELXSI.NS', 'GLAND.NS', 'IDFCFIRSTB.NS', 'PEL.NS', 'APOLLOTYRE.NS',
                    'SUNTV.NS', 'LALPATHLAB.NS', 'WHIRLPOOL.NS', 'ZEEL.NS', 'BATAINDIA.NS', 'COFORGE.NS', 'TVSMOTOR.NS',
                    'ABFRL.NS', 'VOLTAS.NS', 'ABBOTINDIA.NS', 'UBL.NS', 'TRIDENT.NS', 'FEDERALBNK.NS', 'TORNTPOWER.NS',
                    'INDIANB.NS', 'TATACHEM.NS', 'MRF.NS', 'RAMCOCEM.NS', 'COROMANDEL.NS', 'OFSS.NS', 'GUJGASLTD.NS',
                    'MFSL.NS', 'MPHASIS.NS', 'PAYTM.NS', 'TIINDIA.NS', 'NHPC.NS', 'ABCAPITAL.NS', 'ASTRAL.NS',
                    'HONAUT.NS', 'AUROPHARMA.NS', 'CONCOR.NS', 'DALBHARAT.NS', 'LUPIN.NS', 'ZYDUSLIFE.NS',
                    'JINDALSTEL.NS', 'OBEROIRLTY.NS', 'NMDC.NS', 'IPCALAB.NS', 'BHARATFORG.NS', 'TATACOMM.NS',
                    'BALKRISIND.NS', 'POONAWALLA.NS', 'BHEL.NS', 'ALKEM.NS', 'ADANIPOWER.NS', 'INDHOTEL.NS',
                    'JUBLFOOD.NS', 'ESCORTS.NS', 'DELHIVERY.NS', 'CGPOWER.NS', 'NAVINFLUOR.NS', 'SYNGENE.NS',
                    'CUMMINSIND.NS', 'TRENT.NS', 'PERSISTENT.NS', 'IGL.NS', 'DEEPAKNTR.NS', 'MAXHEALTH.NS',
                    'POLICYBZR.NS', 'AUBANK.NS', 'HINDPETRO.NS']
NIFTY200_MOMENTUM_30 = ['COALINDIA.NS', 'AMBUJACEM.NS', 'EICHERMOT.NS', 'BHARTIARTL.NS', 'PNB.NS', 'NTPC.NS', 'M&M.NS',
                        'IDFCFIRSTB.NS', 'CANBK.NS', 'ICICIBANK.NS', 'AXISBANK.NS', 'SIEMENS.NS', 'TVSMOTOR.NS',
                        'FEDERALBNK.NS', 'ABB.NS', 'SBIN.NS', 'BANKBARODA.NS', 'ABCAPITAL.NS', 'JINDALSTEL.NS',
                        'HAL.NS', 'BHEL.NS', 'SUNPHARMA.NS', 'BEL.NS', 'INDHOTEL.NS', 'ESCORTS.NS', 'ITC.NS',
                        'PIDILITIND.NS', 'CUMMINSIND.NS', 'TRENT.NS', 'ADANIENT.NS']
NIFTY_MIDCAP150_QUALITY_50 = ['IEX.NS', 'NAM-INDIA.NS', 'ALKYLAMINE.NS', 'ISEC.NS', 'CROMPTON.NS', 'PETRONET.NS',
                              'AIAENG.NS', 'PFIZER.NS', 'LTTS.NS', 'HINDZINC.NS', 'AJANTPHARM.NS', 'TATAELXSI.NS',
                              'SKFINDIA.NS', 'SANOFI.NS', 'SUNTV.NS', 'LALPATHLAB.NS', 'WHIRLPOOL.NS', 'VINATIORGA.NS',
                              'EMAMILTD.NS', 'COFORGE.NS', 'VOLTAS.NS', 'ABBOTINDIA.NS', 'KANSAINER.NS',
                              'COROMANDEL.NS', 'OFSS.NS', 'GUJGASLTD.NS', 'BAYERCROP.NS', 'TIINDIA.NS', 'ASTRAL.NS',
                              'HONAUT.NS', 'RELAXO.NS', 'KPRMILL.NS', 'KAJARIACER.NS', 'SUPREMEIND.NS', 'IPCALAB.NS',
                              'BALKRISIND.NS', 'CRISIL.NS', 'PAGEIND.NS', 'ATUL.NS', 'APLLTD.NS', 'GSPL.NS',
                              'GRINDWELL.NS', 'NAVINFLUOR.NS', '3MINDIA.NS', 'SOLARINDS.NS', 'PERSISTENT.NS',
                              'DEEPAKNTR.NS', 'APLAPOLLO.NS', 'AUBANK.NS', 'GLAXO.NS']


# def getStocks(Group):
#     match Group:
#         case 'NIFTY_50':
#             return NIFTY_50
#         case 'NIFTY_AUTO':
#             return NIFTY_AUTO
#         case 'NIFTY_DIVIDEND_OPPORTUNITIES_50':
#             return NIFTY_DIVIDEND_OPPORTUNITIES_50
#         case 'NIFTY_PSE':
#             return NIFTY_PSE
#         case 'NIFTY_INDIA_MANUFACTURING':
#             return NIFTY_INDIA_MANUFACTURING
#         case 'NIFTY_GROWTH_SECTORS_15':
#             return NIFTY_GROWTH_SECTORS_15
#         case 'NIFTY100_LIQUID_15':
#             return NIFTY100_LIQUID_15
#         case 'NIFTY50_EQUAL_WEIGHT':
#             return NIFTY50_EQUAL_WEIGHT
#         case 'NNIFTY_PSU_BANK':
#             return NIFTY_PSU_BANK
#         case 'NIFTY_ALPHA_LOW_VOLATILITY_30':
#             return NIFTY_ALPHA_LOW_VOLATILITY_30
#         case 'NIFTY_OIL_AND_GAS':
#             return NIFTY_OIL_AND_GAS
#         case 'NIFTY_MIDCAP_50':
#             return NIFTY_MIDCAP_50
#         case 'NIFTY_ENERGY':
#             return NIFTY_ENERGY
#         case 'NIFTY_INDIA_CONSUMPTION':
#             return NIFTY_INDIA_CONSUMPTION
#         case 'NIFTY_SMALLCAP_250':
#             return NIFTY_SMALLCAP_250
#         case 'NIFTY_SMALLCAP_50':
#             return NIFTY_SMALLCAP_50
#         case 'NIFTY_MICROCAP_250':
#             return NIFTY_MICROCAP_250
#         case 'NIFTY_METAL':
#             return NIFTY_METAL
#         case 'NIFTY100_QUALITY_30':
#             return NIFTY100_QUALITY_30
#         case 'NIFTY50_VALUE_20':
#             return NIFTY50_VALUE_20
#         case 'NIFTY_LARGEMIDCAP_250':
#             return NIFTY_LARGEMIDCAP_250
#         case 'NIFTY_MIDCAP_150':
#             return NIFTY_MIDCAP_150
#         case 'NIFTY_MNC':
#             return NIFTY_MNC
#         case 'NIFTY_100':
#             return NIFTY_100
#         case 'NIFTY_COMMODITIES':
#             return NIFTY_COMMODITIES
#         case 'NIFTY100_ESG':
#             return NIFTY100_ESG
#         case 'NIFTY_MIDCAP_SELECT':
#             return NIFTY_MIDCAP_SELECT
#         case 'NIFTY_FMCG':
#             return NIFTY_FMCG
#         case 'NIFTY_PHARMA':
#             return NIFTY_PHARMA
#         case 'NIFTY_REALTY':
#             return NIFTY_REALTY
#         case 'NIFTY100_EQUAL_WEIGHT':
#             return NIFTY100_EQUAL_WEIGHT
#         case 'NIFTY_200':
#             return NIFTY_200
#         case 'NIFTY_BANK':
#             return NIFTY_BANK
#         case 'NIFTY_MIDCAP_LIQUID_15':
#             return NIFTY_MIDCAP_LIQUID_15
#         case 'NIFTY_CPSE':
#             return NIFTY_CPSE
#         case 'NIFTY_FINANCIAL_SERVICES':
#             return NIFTY_FINANCIAL_SERVICES
#         case 'NIFTY_MIDSMALLCAP_400':
#             return NIFTY_MIDSMALLCAP_400
#         case 'NIFTY_SMALLCAP_100':
#             return NIFTY_SMALLCAP_100
#         case 'NIFTY_INDIA_DIGITAL':
#             return NIFTY_INDIA_DIGITAL
#         case 'NIFTY_INFRASTRUCTURE':
#             return NIFTY_INFRASTRUCTURE
#         case 'NIFTY_ALPHA_50':
#             return NIFTY_ALPHA_50
#         case 'NIFTY_SERVICES_SECTOR':
#             return NIFTY_SERVICES_SECTOR
#         case 'NIFTY_TOTAL_MARKET':
#             return NIFTY_TOTAL_MARKET
#         case 'NIFTY_NEXT_50':
#             return NIFTY_NEXT_50
#         case 'NIFTY_IT':
#             return NIFTY_IT
#         case 'NIFTY500_MULTICAP_50_25_25':
#             return NIFTY500_MULTICAP_50_25_25
#         case 'NIFTY_MEDIA':
#             return NIFTY_MEDIA
#         case 'NIFTY200_QUALITY_30':
#             return NIFTY200_QUALITY_30
#         case 'NIFTY_PRIVATE_BANK':
#             return NIFTY_PRIVATE_BANK
#         case 'NIFTY_FINANCIAL_SERVICES_25_50':
#             return NIFTY_FINANCIAL_SERVICES_25_50
#         case 'NIFTY_HEALTHCARE_INDEX':
#             return NIFTY_HEALTHCARE_INDEX
#         case 'NIFTY_MIDCAP_100':
#             return NIFTY_MIDCAP_100
#         case 'NIFTY200_MOMENTUM_30':
#             return NIFTY200_MOMENTUM_30
#         case 'NIFTY_MIDCAP150_QUALITY_50':
#             return NIFTY_MIDCAP150_QUALITY_50

def returnGroupList():
    return ['NIFTY_AUTO', 'NIFTY_DIVIDEND_OPPORTUNITIES_50', 'NIFTY_PSE', 'NIFTY_INDIA_MANUFACTURING',  'NIFTY_GROWTH_SECTORS_15',  'NIFTY100_LIQUID_15',  'NIFTY50_EQUAL_WEIGHT',  'NIFTY_PSU_BANK',  'NIFTY_OIL_AND_GAS',  'NIFTY_MIDCAP_50',  'NIFTY_ENERGY',  'NIFTY_SMALLCAP_250',  'NIFTY_SMALLCAP_50',  'NIFTY_MICROCAP_250',  'NIFTY_METAL',  'NIFTY100_QUALITY_30',  'NIFTY50_VALUE_20',  'NIFTY_LARGEMIDCAP_250',  'NIFTY_MIDCAP_150',  'NIFTY_100',  'NIFTY100_ESG',  'NIFTY_MIDCAP_SELECT',  'NIFTY_PHARMA',  'NIFTY_REALTY',  'NIFTY_200',  'NIFTY100_LOW_VOLATILITY_30',  'NIFTY_BANK',  'NIFTY_MIDCAP_LIQUID_15',  'NIFTY_CPSE',  'NIFTY_FINANCIAL_SERVICES',  'NIFTY_MIDSMALLCAP_400',  'NIFTY_SMALLCAP_100',  'NIFTY_INDIA_DIGITAL',  'NIFTY_INFRASTRUCTURE',  'NIFTY_ALPHA_50',  'NIFTY_SERVICES_SECTOR',  'NIFTY_50',  'NIFTY_TOTAL_MARKET',  'NIFTY_NEXT_50',  'NIFTY_IT',  'NIFTY500_MULTICAP_50_25_25',  'NIFTY_MEDIA',  'NIFTY_PRIVATE_BANK',  'NIFTY_FINANCIAL_SERVICES_25_50',  'NIFTY_HEALTHCARE_INDEX',  'NIFTY_MIDCAP_100',  'NIFTY200_MOMENTUM_30',  'NIFTY_MIDCAP150_QUALITY_50']

def getStocksOldWay(group):
    group_code = {
        'NIFTY_AUTO':NIFTY_AUTO,
        'NIFTY_DIVIDEND_OPPORTUNITIES_50':NIFTY_DIVIDEND_OPPORTUNITIES_50,
        'NIFTY_PSE':NIFTY_PSE,
        'NIFTY_INDIA_MANUFACTURING':NIFTY_INDIA_MANUFACTURING,
        'NIFTY_GROWTH_SECTORS_15':NIFTY_GROWTH_SECTORS_15,
        'NIFTY100_LIQUID_15':NIFTY100_LIQUID_15,
        'NIFTY50_EQUAL_WEIGHT':NIFTY50_EQUAL_WEIGHT,
        'NIFTY_PSU_BANK':NIFTY_PSU_BANK,
        'NIFTY_OIL_AND_GAS':NIFTY_OIL_AND_GAS,
        'NIFTY_MIDCAP_50':NIFTY_MIDCAP_50,
        'NIFTY_ENERGY':NIFTY_ENERGY,
        'NIFTY_SMALLCAP_250':NIFTY_SMALLCAP_250,
        'NIFTY_SMALLCAP_50':NIFTY_SMALLCAP_50,
        'NIFTY_MICROCAP_250':NIFTY_MICROCAP_250,
        'NIFTY_METAL':NIFTY_METAL,
        'NIFTY100_QUALITY_30':NIFTY100_QUALITY_30,
        'NIFTY50_VALUE_20':NIFTY50_VALUE_20,
        'NIFTY_LARGEMIDCAP_250':NIFTY_LARGEMIDCAP_250,
        'NIFTY_MIDCAP_150':NIFTY_MIDCAP_150,
        'NIFTY_100':NIFTY_100,
        'NIFTY100_ESG':NIFTY100_ESG,
        'NIFTY_MIDCAP_SELECT':NIFTY_MIDCAP_SELECT,
        'NIFTY_PHARMA':NIFTY_PHARMA,
        'NIFTY_REALTY':NIFTY_REALTY,
        'NIFTY_200':NIFTY_200,
        'NIFTY100_LOW_VOLATILITY_30':NIFTY100_LOW_VOLATILITY_30,
        'NIFTY_BANK':NIFTY_BANK,
        'NIFTY_MIDCAP_LIQUID_15':NIFTY_MIDCAP_LIQUID_15,
        'NIFTY_CPSE':NIFTY_CPSE,
        'NIFTY_FINANCIAL_SERVICES':NIFTY_FINANCIAL_SERVICES,
        'NIFTY_MIDSMALLCAP_400':NIFTY_MIDSMALLCAP_400,
        'NIFTY_SMALLCAP_100':NIFTY_SMALLCAP_100,
        'NIFTY_INDIA_DIGITAL':NIFTY_INDIA_DIGITAL,
        'NIFTY_INFRASTRUCTURE':NIFTY_INFRASTRUCTURE,
        'NIFTY_ALPHA_50':NIFTY_ALPHA_50,
        'NIFTY_SERVICES_SECTOR':NIFTY_SERVICES_SECTOR,
        'NIFTY_50':NIFTY_50,
        'NIFTY_TOTAL_MARKET':NIFTY_TOTAL_MARKET,
        'NIFTY_NEXT_50':NIFTY_NEXT_50,
        'NIFTY_IT':NIFTY_IT,
        'NIFTY500_MULTICAP_50_25_25':NIFTY500_MULTICAP_50_25_25,
        'NIFTY_MEDIA':NIFTY_MEDIA,
        'NIFTY_PRIVATE_BANK':NIFTY_PRIVATE_BANK,
        'NIFTY_FINANCIAL_SERVICES_25_50':NIFTY_FINANCIAL_SERVICES_25_50,
        'NIFTY_HEALTHCARE_INDEX':NIFTY_HEALTHCARE_INDEX,
        'NIFTY_MIDCAP_100':NIFTY_MIDCAP_100,
        'NIFTY200_MOMENTUM_30':NIFTY200_MOMENTUM_30,
        'NIFTY_MIDCAP150_QUALITY_50':NIFTY_MIDCAP150_QUALITY_50
    }
    return group_code.get(group)
